CONTRIBUTING.md

Removed reference to Bitbucket and replaced it with Github

---

README.md
docs/source/install/install_local.rst

I made 2 small improvements to the documentation:
- Added the badges at the head of the README
- Corrected problems with the installation instructions in the online documentation

Better documentation

---

fbpic/fields/cuda_methods.py
fbpic/fields/fields.py
fbpic/main.py

As explained in the issue, the aim of this PR is to simplify the code.

Close #13: Remove the option `ptcl_feedback` in the field push

---

fbpic/boundaries/particle_buffer_handling.py

I just corrected the bug that @Escapado reported. 
As can be seen in the modified code, the error was due to a rather significant error in the particle exchange. 
With the new code, here is map of the fields:
Could you double-check that you get the same results with this branch, on your side?
If yes, you can then merge this branch.

Close #23: Periodic boundaries seem broken in dev branch

---

docs/source/example_input/lwfa_script.py
docs/source/example_input/parametric_script.py

As discussed here is a pull request to close issue #39.

Close #39: Checkpoints with external beams

---

tests/test_periodic_plasma_wave.py

This pull request adds a test of the charge conservation to the periodic plasma wave.
Because the simulation is periodic and we never cut the stencil, charge conservation should be satisfied to a precision close to the machine precision (when the current correction is used).

Add test of charge conservation

---

tests/test_periodic_plasma_wave.py

As discussed, this activates the plasma periodic wave with 3rd order shape factor.

Close #87:  Test the 3rd gathering function in the automated tests

---

README.md
docs/source/how_to_run.rst
docs/source/index.rst
docs/source/install/install_cori.rst
docs/source/install/install_lawrencium.rst
docs/source/install/installation.rst

This closes #84:
- The documentation is updated in order to reflect the fact that multi-threading is available.
- Installation instructions have been updated for Cori and Lawrencium.

Update documentation for multi-threading

---

fbpic/boundaries/moving_window.py
fbpic/openpmd_diag/cuda_methods.py
fbpic/particles/deposition/cuda_methods.py
fbpic/particles/particles.py
fbpic/particles/push/cuda_methods.py

This pull request fixes a few bugs that were introduced recently, and caused the code to fail on GPU.
With this PR, all the automated tests now pass on GPU.

Close #103 Current `dev` branch fails to compile on GPU

---

README.md
docs/source/index.rst
docs/source/install/install_local.rst

@soerenjalas @MKirchen : This is an attempt but is definitely open for modifications, additions, suggestions, etc...

Brag (a little bit) about fbpic's feature in the README

---

docs/source/example_input/boosted_frame_script.py
docs/source/example_input/lwfa_script.py
docs/source/overview.rst
fbpic/main.py

From discussion with some users, it seems that `n_order` is not always easy to understand. This PR does some minor clarification in the comments/docstring, and, more importantly,  provides a reference for users that need more information.

Clarify the discussion of n_order

---

fbpic/fields/spectral_transform/fourier.py
fbpic/fields/spectral_transform/spectral_transformer.py

When creating an `FFTW` object, the object is tied to a given input and an output array, which have to be created before the object. For this reason, in the current code, any fourier transform also involves copying data into these given input and output array. 
However, this is in fact not necessary: I realized that the `FFTW` object has a method that allows to point directly to different input and output arrays (i.e. no copying needed). This PR uses this new method to simplify the code. 
Also, as a consequence, the spectral buffers (which hold the data **between** a DHT and FFT) do not need to be created in the `fourier.py` and are created instead in the `spectral_transformer.py`, which is more natural.

Simplify pyfftw code

---

fbpic/print_utils.py

This uses the fact that we have usually 2 distinct MPI "communicators" in an FBPIC run:
- The global `MPI.COMM_WORLD`: which is either the global `mpi4py` communicator, or an instance of `DummyCommunicator` (when `mpi4py` is not installed).
- The communicator that the simulation actually uses: `sim.comm.mpi_comm`: which is either the global `mpi4py` communicator, or `None` (for single-proc simulations ; e.g. when `use_all_mpi_ranks` is False) ; at some point, this could also be an MPI group.
When printing the GPU names, it would not be ideal to call Barrier with the **global** `MPI.COMM_WORLD`. This is because the code for printing the GPU names is called when creating the `Simulation` object, and because when running a set of simulations with `use_all_ranks=False`, different MPI ranks …

Close #164 New printing functions break when mpi is not installed, for `verbose_level=2`

---

fbpic/fields/fields.py

These functions date from when the code was still experimental.
I don't think that they are useful anymore, and they make the code longer/less readable. Would you be okay to remove them?

Remove old plotting functions

---

docs/source/overview.rst
fbpic/main.py

Now that the arbitrary number of modes has been implemented and tested (See #194), I think we can add it to the documentation.

Update documentation for arbitrary number of modes

---

fbpic/utils/printing.py

Currently, when running on GPU and with MPI, the code outputs information about the node on which each MPI rank is running (in addition to the GPU id).
This information is also useful also when running on CPU (in order to check that there is e.g. only one MPI per socket). This PR implements the corresponding changes.

Print information about CPU distribution

---

fbpic/boundaries/boundary_communicator.py

This PR removes the non-ideal global Barrier() statements that were used in the MPI communication to synchronize ranks for performance and fail-safety reasons. Also, the MPI Wait() pattern for the non-blocking communications (Isend and Irecv) have been updated. Now the code waits for requests for each of the non-blocking commands. This seems to be required for good performance and correct behaviour when not using global Barrier() synchronization.
Three different cases have been benchmarked (average time per step) with the script attached below.
Setup: JURECA, 2x4 = 8xK80 on 2 nodes with 8 MPI processes.
1) Barrier() and old Wait() pattern (master):    94 ms 
2) no Barrier() and old Wait() pattern:    168 ms and MPI error at the end
3) no Barrier() and new Wait() pattern (this PR):    90 …

Removed Barrier() statements and updated Wait() pattern in MPI communication

---

docs/source/how_to_run.rst
fbpic/boundaries/boundary_communicator.py
fbpic/boundaries/field_buffer_handling.py
fbpic/main.py
fbpic/utils/mpi.py
fbpic/utils/printing.py

Revert "[WIP] Add CUDA GPUDirect support for direct GPU MPI communication"

---

docs/source/how_to_run.rst
fbpic/boundaries/boundary_communicator.py
fbpic/boundaries/field_buffer_handling.py
fbpic/main.py
fbpic/utils/mpi.py
fbpic/utils/printing.py

This pull request reimplements PR #219 (which was reverted by PR #225 because some tests were observed to fail, on machines that support GPUDirect).

Implement cuda-aware MPI communications

---

fbpic/fields/cuda_methods.py
fbpic/fields/fields.py
fbpic/fields/interpolation_grid.py
fbpic/fields/psatd_coefs.py
fbpic/fields/spectral_grid.py
tests/test_laser_envelope.py

This is a continuation of PR 250, thus it should be merged only after having merged the PR250.
Here we continued developing the envelope model by adding the possibility of using cuda and GPU to push the fields and transform them between Interpolation and Spectral grids.
The code is very similar to the one used for the fields.
The code still doesn't include any of the following features:
-Any interactions with the plasma
-MPI use
-Comoving approach (Note: the envelope model as of now is not valid for high boosts)
-Handling moving windows
-Boundary conditions

GPU implementation for pushing the laser envelope

---

docs/source/overview.rst
fbpic/main.py

Based on feedback from users and recent experience with the code, I just added a few safeguards and update to the documentation.

Minor updates to the documentation and safe-guards

---

README.md

I think harware is supposed to be hardware.
thanks,
-isaiah

Minor spelling

---

fbpic/openpmd_diag/particle_diag.py

Added "subsampling_fraction" to apply_selection function.
select particles randomly based on on subsampling_fraction.
numpy module.
checked with pep8, pyflakes and tested with setup.py test

Subsampling

---

docs/source/install/install_summit.rst
docs/source/install/installation.rst

Here are the instructions for running on Summit (PowerPC with V100 GPUs).

Add installation instructions for Summit

---

fbpic/lpa_utils/bunch.py

Currently, if the space charge calculation routine is called for a species that has *no macroparticle*, the resulting fields will be filled with NaNs. (This is because the routine calculates an average `gamma`, which is itself NaN, and uses it in the Poisson solver.)
This case can come up easily: for instance, if the parameters of `add_gaussian_bunch` are not quite correct, the bunch might be outside of the simulation box, and the corresponding species will have no macroparticle.
This PR fixes the issue by checking that the number of particle is non-zero. (Otherwise, it raises a warning and skips the space-charge calculation.)
In addition, I made the calculation of the mean gamma more correct by taking into account the particle weight (for cases where not all particles have the same …

Make space-charge calculation more robust

---

fbpic/openpmd_diag/checkpoint_restart.py
fbpic/particles/particles.py

Currently, the arrays `cell_idx`, `sorted_idx` and `prefix_sum` are always initialized on the CPU, and copied to/from the GPU just like the other particle quantities (`x`, `uy`, `Ez`, etc.).
However, unlike these other particle quantities, these arrays are never accessed on CPU (e.g. they are never written in the diagnostics, and never sent via MPI).
Thus, initializing these arrays directly on GPU - and always keeping them there - would save some CPU-GPU copies.

Keep sorting arrays on GPU

---

fbpic/main.py

Hi, I'm reading through the code for educational purposes :wink: and there's a couple of very small simplifications, plus a typo fix, that I found could easily be done.

Very small text fixes

---

fbpic/openpmd_diag/checkpoint_restart.py

In the upcoming version 1.0 of openPMD-viewer (not yet released), the particle positions will be returned in meters directly (instead of microns), and the name of the package will change from `opmd_viewer` to `openpmd_viewer`. Therefore, the FBPIC code for restarting (from a checkpoint) - which uses openPMD-viewer - needs to be adapted.
This PR changes that code so that it can work both with version 1.0 and the old version 0 of openPMD-viewer.

Allow restart to work with upcoming openPMD-viewer 1.0

---

docs/source/advanced/profiling.rst

Nvidia released a new profiling tools (Nsight Systems).
This adds instructions on how to profile with NSight Systems.

Add instructions for Nsight Systems

---

fbpic/boundaries/boundary_communicator.py
fbpic/boundaries/cuda_methods.py

This is still a PR where we simply prepare mundane functions for the PML fields : in this case damping in the z direction.

Damp PML field in the z direction

---

fbpic/picmi/simulation.py

Update naming of moving window velocity

---

docs/source/advanced/3d_visualization.rst
fbpic/lpa_utils/bunch.py
fbpic/openpmd_diag/checkpoint_restart.py
tests/test_beam_focusing.py
tests/test_boosted_particle_output.py
tests/test_cpu_gpu_deposition.py
tests/test_example_docs_scripts.py
tests/test_ionization.py
tests/test_pml.py
tests/test_space_charge.py

This PR makes a number of changes required for FBPIC (and its tests) to work with openPMD-viewer 1.0.0

Updates for openPMD-viewer 1.0.0

---

fbpic/utils/threading.py

Add environment variable to disable caching

---

docs/source/overview/pic_algorithm.rst

This changes the documentation, in order to warn users of the side-effect of our new deposition scheme (#347).

Document the non-uniformity close to the axis

---

fbpic/utils/cuda.py

This PR fixes the issues reported in #481

Fix incompatibility between FBPIC and numba 0.51+

---

fbpic/lpa_utils/external_fields.py

This PR fixes #497 regarding the application of external fields for multiple species (see there). I tested it and in my case, the problem was gone.

Fixed external fields for multiple species

---

README.md
docs/source/index.rst

This adds the reference both in the README and in the documentation.

Add reference to latest article on finite-order Galilean

---

fbpic/utils/cuda.py

Results in small performance increase.
Closes #506.

Force TPB values for V100 to apply for A100

---

fbpic/picmi/simulation.py

The API recently slightly changed in PICMI 0.0.18. This changes FBPIC accordingly.

Fixes for PICMI 0.0.18

---

fbpic/openpmd_diag/inputscript_diag.py

Added missing default argument; when initialising with dt_period would need to set period=None manually otherwise

Added missing default argument

---

docs/source/install/install_local.rst
fbpic/picmi/simulation.py

PICMI recently changed its convention for the moving window:
https://github.com/picmi-standard/picmi/pull/54

Implement compatibility with latest version of PICMI

---

fbpic/openpmd_diag/boosted_field_diag.py
fbpic/openpmd_diag/boosted_particle_diag.py

This PR adds the possibility to limit the creation of snapshots to a specific time interval (in the lab frame) when using the back-transformed diagnostics in Lorentz-boosted frame simulations. 
The time interval is defined by two new parameters `t_min_snapshots_lab` and `t_max_snapshots_lab`. The parameters are similar to `iteration_min` and `iteration_max` in the standard OpenPMD diagnostics.
Note that the functionality of this PR can also be mimicked by deleting snapshots from the list of snapshots after creating them. For example:
```
sim.diags = [ BackTransformedFieldDiagnostic( ... ), ... ]
del sim.diags[0].snapshots[:3]
```
Therefore, it is up to debate if this PR is really necessary.

Limit snapshot creation to time interval in back-transformed diagnostics
