fbpic/fbpic

- .travis.yml
- CONTRIBUTING.md
- README.md
- docs/source/install/install_jureca.rst
- docs/source/install/install_local.rst
- fbpic/fields/fields.py
- requirements.txt
- setup.py
Before this PR, matplotlib was imported by default by fbpic (in `fields.py`). However, it is only used for some plots of the fields, which were used when developing the code, but are never used in production.
Since the latest version of matplotlib take quite some time to be imported, this PR stops importing matplotlib by default (so as not to slow down production runs). matplotlib is now only imported when using the above-mentioned plotting functions.
As a consequence, matplotlib was also removed from the dependencies of fbpic (and from the corresponding documentation). It is now only installed for running the tests (since the tests do still use matplotlib)
PS: Either of the three of you can merge this PR.
> Avoid importing matplotlib in production runs

- .travis.yml
This PR modifies the Travis CI so that they run in a conda environment.
The main motivation is to ensure that the python which is used to run the test is indeed the intended python (i.e. python 2.7 and python 3.5 respectively, for the two set of tests that we run)
> Run the Travis CI tests in a conda environment

- fbpic/boundaries/boundary_communicator.py
For single-proc, periodic simulations, we used to skip the particle exchange, using:
``` python
if self.n_guard == 0:
return
```
However, that also means that we were skipping these instructions, which make sure that 
particles are brought back inside the box.
``` python
if self.right_proc == 0:
recv_right[2,:] = recv_right[2,:] + self.Ltot
if self.left_proc == self.size-1:
recv_left[2,:] = recv_left[2,:] - self.Ltot
```
This can cause problems in periodic simulations with a flowing plasma: the particles continuously move, and their positions are never brought back inside the box. This can then cause errors (which I observed) in the charge deposition, due to out-of-bound access.
(Note: the charge deposition can handle particles that are moderately far outside the box, thanks to:
``` …
```
> Prevent particles from getting too far out of the box, in the periodic case

- docs/source/index.rst
- fbpic/openpmd_diag/boosted_field_diag.py
This includes two small changes:
- Remove the note in the documentation that said that the Galilean scheme is not implemented.
- By default, do not output rho and J in the boosted field diagnostic.
The second change is not ideal, but it is motivated by the fact that I often observed rho and J to be quite noisy and hard to interpret in the backward-transformed diagnostics (whereas they are fine in the untransformed diagnostics, i.e. the diagnostics within the boosted frame). This is clearly an artifact of the backward transformation for the staggered field rho and J. 
So the current default is a safe-guard for new users, so that they do not get those weird fields and wonder what happens.  Of course, they can always override this default, but in this case they will (hopefully) read the …
> Minor changes to the galilean documentation

- .travis.yml
- fbpic/fields/cuda_methods.py
- fbpic/fields/fields.py
- fbpic/fields/numba_methods.py
This pull request creates numba functions for the field push and the current correction, when done on the CPU.
It also reintroduces the standard PSATD functions that were replaced by the galilean/comoving functions. This is for the sake of simplicity, for users that are only interested in the standard PSATD.
Note: I did not include the change that @MKirchen requested regarding setting V to None for the standard PSATD scheme. This is because I did not want this PR to become too big. I will include this in a future PR.
> Close #12 and #14: Build numba function for field push and keep the ones for standard PSATD

- fbpic/openpmd_diag/boosted_particle_diag.py
I am currently working on implementing the boosted diagnostics for multi-CPU and multi-GPU simulations, as it is currently needed for one of our users. (Note that the regular diagnostics are implemented for multi-CPU/GPU simulations (via MPI gather to the first proc), but when we implemented the boosted diagnostics, we skipped it for the sake of rapidity of the implementation).
The current pull request does not implement this directly, but is a minor change in preparation for it.
In the current pull request, I slightly modify the structure of the data. Throughout the different operations that we do on the data (interpolation at a given time, Lorentz-transform, selection of particles, etc.) we use arrays of size (8, num_particles) where the 8 corresponds to the number of particle …
> Remove `inv_gamma` from the `slice_array` in the boosted diagnostics

- docs/source/example_input/boosted_frame_script.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- tests/test_example_docs_scripts.py
This generalizes the boosted-frame output to the case of a multi-CPU or multi-GPU.
The implementation is similar to that of [Warp](https://bitbucket.org/berkeleylab/warp).
More specifically, the data that needs to be written is cached on each processor until the simulation reaches an output iteration (as defined by the parameter `diag_period`). Then this cached data is gathered on rank 0, and rank 0 writes the data to disk.
Note: I also modified the boosted-frame example input script (to make it faster to run), and switched the boosted-frame automated test from single proc to two-proc. (So that the parallel boosted frame output are automatically tested for each push.)
> Parallel boosted frame output

- fbpic/lpa_utils/laser/antenna.py
- fbpic/main.py
- fbpic/particles/cuda_deposition/cubic.py
- fbpic/particles/cuda_deposition/linear.py
- fbpic/particles/cuda_deposition/linear_non_atomic.py
- fbpic/particles/cuda_methods.py
- fbpic/particles/numba_methods.py
- fbpic/particles/particles.py
- fbpic/particles/utility_methods.py
- tests/test_laser_antenna.py
Hi Kevin,
Here are a few suggested changes to the pull request on 3rd order shape factor (except for the files `linear.py` and `cubic.py`, for which I will propose changes in a separate pull request).
Feel free to reject/discuss some of these changes, they are only suggestions.
Here are the main changes:
- I added you name to the files you changed (in the header)
- I rephrased some of the docstrings and some of the inline comments (this is me being very picky ; sorry!)
- In the CPU function `weights`, I used 2darrays directly instead of lists of 1darrays which are later converted to 2darrays. I am not sure it is much faster, but it makes the implementation slightly more compact.
- I reverted the changes that I made to the file `test_laser.py` (I previously added tests that initialize the …
> Proposed changes to 3rd order implementation in all files except `linear.py` and `cubic.py`

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/main.py
This pull request solves issue #25 (Test of Cherenkov instability yields different result on the GPU).
The issue appeared in the case of a single-proc, periodic simulation, when the bulk of the plasma has a non-zero velocity. In this case, the particles progressively go out of the box. In principle, the pull request #9 (Prevent particles from getting too far out of the box, in the periodic case) should take care of that by forcing the exchange of particles even in the single-proc, periodic case. However, the changes of pull request #9 only work on the CPU (this is because, on the GPU, the exchange of particles relies on the presence of guard cells, but no guard cells are present in the single-proc, periodic case.)
Therefore, instead of using the standard particle exchange, the present …
> Close #25 : Fix single-proc periodic simulations on GPU

- fbpic/lpa_utils/bunch.py
I thought now that we have this nice unified file format we might also want to leverage it as an input format for FBPIC. Therefore, I wrote and additional `add_elec_bunch` method which loads a particle distribution from an openPMD time-series and initialises it with corresponding space charge fields.
Just like the checkpoint method it uses the openPMD-viewer. 
Let me know if you think this is useful or not or if you want any changes made to the code.
> Add method to load particle distribution from openPMD hdf5 file

- docs/source/example_input/boosted_frame_script.py
- docs/source/example_input/parametric_script.py
- fbpic/openpmd_diag/checkpoint_restart.py
- tests/test_example_docs_scripts.py
As reported by @soerenjalas, the checkpoints were not working when `use_all_mpi_ranks=False`, because the `BoundaryCommunicator` object does not contain an MPI communicator (in order to prevent the independent simulations from talking to each other).
However, when writing the checkpoints, the independent simulations do need to synchronize, in order to prepare the output folders. I fixed the issue by using the global MPI communicator **only** in the checkpoint code (see the file `checkpoint_restart.py`).
I also expanded the automatic tests so that they test the checkpoint/restart in the case of `use_all_mpi_ranks=False`.
The list of changes for this pull request is somewhat messy, because (as usual) Atom linted the code to remove trailing spaces and empty lines. Sorry about this. The only …
> Close #36 Checkpoints not working with use_all_mpi_ranks = False

- fbpic/openpmd_diag/field_diag.py
- fbpic/openpmd_diag/generic_diag.py
- fbpic/openpmd_diag/particle_diag.py
This is a very minor pull request: for a `ParticleDiagnostic` or `FieldDiagnostic` instance, it allows the user to specify the min and max iterations between which this diagnostic should be active. 
A typical use case would be to produce diagnostics with a higher output frequency at a specific moment of the simulation (e.g. when injection happens). In order to do so, the user would create two instances of e.g. `ParticleDiagnostic`:
- One with low output frequency (i.e. high `period`)
- One with high output frequency and specific `iteration_min` and `iteration_max`
> OpenPMD diagnostics: specify min and max iterations

- docs/source/example_input/lwfa_script.py
- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/field_buffer_handling.py
- fbpic/boundaries/moving_window.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/openpmd_diag/checkpoint_restart.py
- fbpic/openpmd_diag/data_dict.py
- fbpic/openpmd_diag/particle_diag.py
- fbpic/particles/particles.py
- fbpic/particles/tracking/__init__.py
- fbpic/particles/tracking/tracking.py
- tests/test_example_docs_scripts.py
This pull request adds particle tracking to `fbpic`: when activated, a unique ID is attributed to each macroparticles (including new macroparticles created by the moving window) and these ID are written in the openPMD file, so that particles can be tracked in postprocessing, using the openPMD-viewer (see https://github.com/openPMD/openPMD-viewer/pull/139)
This pull request is compatible with:
- the GPU implementation (the array of particle ID is updated whenever the particles are sorted)
- MPI communications (the arrays of particle ID are communicated via MPI)
- Checkpoint / restarts (when restarting from a checkpoint that contains particle ID, the simulation automatically loads these particle ID and tracks the corresponding species)
In order to activate tracking for a given species, use: …
> Particle tracking

- fbpic/lpa_utils/bunch.py
- tests/unautomated/test_space_charge_gaussian.py
The function `np.random.normal(gamma, sig_gamma, N)` will throw a ValueError if sig_gamma<=0.
However a user might desire to initialise a bunch with a constant energy so this PR is meant to implement that by simply filling a numpy array of desired size with the desired value for each entry by using [numpy.full()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html). If the user selected a negative energy spread it will be set to zero and a warning is given.
Furthermore I updated the corresponding test file as it threw errors at me because Python 3.5 handles integer division differently than Python 2.x.
> Fix gaussian beam initialization for zero energy spread and update test file

- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/boosted_particle_diag.py
When we use the flag `use_all_mpi_rank=False` with the boosted-frame, the calls to the MPI gathering routines in the boosted-frame output cause the code to crash because the MPI communicator is `None` in this case. This pull request avoids this problem.
> Prevent calls gathering functions when the simulation is single-proc

- tests/test_ionization.py
**Please merge #41, as it will make this pull request much easier to review**
This pull request adds an automated test of the ionization routines: a laser pulse propagates through a jet of Nitrogen atoms, and ionizes the atoms. For the parameters of the laser (which were taken from Chen, JCP, 2013), the final fraction of atoms in the level N5+ is about 33%.
This is successfully tested both in the lab frame and in the boosted frame.
> Add automated test of the ionization routines

- fbpic/main.py
- fbpic/openpmd_diag/checkpoint_restart.py
At the end of the `__init__` function of the `Simulation` object, as well just after a restart, we used to calculate `rho_prev` (for the purpose of current correction). However, this was:
- Inefficient (because it is was done on the CPU, even when a GPU is available)
- Useless (because it was done again in the `step` function, due to the code on particle exchange / moving window, which gets called on the very first iteration of the PIC loop)
- Sometimes incorrect (because we might add new charged particles to the simulation between the initialization and the first call to the `step` function.)
Therefore, I removed the call to `deposit(rho_prev)` in the `__init__` function and the restart code. Also, in the `step` function, I explicitly imposed that on the first iteration of the loop, …
> Remove calculation of `rho_prev` from initialization and restart

- fbpic/lpa_utils/boosted_frame.py
- fbpic/lpa_utils/laser/antenna.py
- fbpic/lpa_utils/laser/laser.py
- fbpic/lpa_utils/laser/profiles.py
This simplifies the expression for a gaussian laser pulse:
- The expression uses complex numbers, which makes it simpler and more compact.
- In the boosted-frame case, we convert the points at which to calculate the laser to the lab-frame, instead of converting the wavelength, radius of curvature etc. to the boosted-frame.
In addition, I added the possibility to add temporal chirp (and a CEP phase) in the laser.
> Simplify laser profile function and add temporal chirp

- fbpic/lpa_utils/external_fields.py
When external fields, and when on of the species is empty (i.e. contains no macroparticles), then the code crashes on GPU. This is apparently because `numba.vectorize` does not support empty arrays as arguments when `target` is `'cuda``.  
This caused the automated tests for ionization to crash on the GPU.
The current pull request implements a fix by simply checking whether the species is empty before applying the fields.
> Only apply external fields to a species if this species has macroparticles

- docs/source/api_reference/lpa_utilities.rst
- fbpic/lpa_utils/boosted_frame.py
- fbpic/lpa_utils/bunch.py
Currently, the user can inject a particle bunch in an FBPIC simulation by passing the particle coordinates in a text file or openPMD file. However, it would be convenient to also have the possibility to pass numpy arrays directly.
This pull request implements a function that takes numpy array as argument. 
In addition, this function can also be used inside the other `add_elec_bunch_...` functions, in order to make them shorter.
> Added bunch initialization from numpy arrays

- docs/source/advanced/advanced.rst
- docs/source/advanced/parameter_scans.rst
- docs/source/advanced/profiling.rst
- docs/source/index.rst
The new section includes:
- how to profile the code on CPU and GPU
- how to run several separate simulations in parallel (this was not previously described in the documentation, but is often useful).
You can have a preview of the documentation by doing `make html` in the directory `docs` (see the `README` for the dependencies).
> Add a section on "Advanced use" in the documentation

- docs/source/example_input/boosted_frame_script.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/openpmd_diag/cuda_methods.py
- fbpic/openpmd_diag/data_dict.py
- fbpic/openpmd_diag/particle_diag.py
- setup.py
- tests/test_example_docs_scripts.py
The aim of this pull request is to add optional integer arrays (like the ionization level, and the particle IDs) to the boosted-frame diagnostics. 
Because the boosted-frame diagnostics used to store (buffer) the quantities in a **2d array of floats** (where the first dimension correspond to the particle quantity and the second corresponds to individual macroparticles), I had to change the data structures in the boosted-frame diagnostics. I now use dictionaries, whose keys are particle quantities (e.g. 'x', 'ux', 'id', etc.) and whose values are 1d arrays (either of float or integers).
This change lead to substantial modifications in the code.
- Dictionaries containing 1d arrays are now used everywhere in the boosted-diagnostics.
- The quantity `self.array_quantities_dict` (which contains …
> Reorganize ParticleDiagnostic and BoostedParticleDiagnostic 

- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/openpmd_diag/particle_diag.py
When using the `ParticleDiagnostic`, the user passes the species that need to be written as a dictionary. Then, internally, the code loops over species (e.g. in order to do MPI Gather) by looping over the keys of the dictionary. 
However, this is a very bad practice, since the keys of a dictionary do not have a well-defined order in Python. This means that different MPI proc could loop over species in different order. 
This PR fixes the problem by using the attribute `species_names_list`, which has a well-defined order.
> Removed the use of `keys()` when looping through species

- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/openpmd_diag/cuda_methods.py
The boosted-frame diagnostics were not taking into account the fact that, for ionizable particles, `w` is the product of the number of physical particles represented **with the ionization level**. 
This pull request fixes this by using `neutral_weight` instead, which is simply the number of physical particles represented.
> Fixed boosted diagnostics of the weights on GPU

- fbpic/boundaries/field_buffer_handling.py
- fbpic/boundaries/guard_cell_damping.py
- fbpic/boundaries/moving_window.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/cuda_utils.py
- fbpic/fields/fields.py
- fbpic/fields/spectral_transform/fourier.py
- fbpic/fields/spectral_transform/hankel.py
- fbpic/fields/spectral_transform/spectral_transformer.py
- fbpic/lpa_utils/external_fields.py
- fbpic/lpa_utils/laser/antenna.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/particles/ionization/inline_functions.py
- fbpic/particles/ionization/ionizer.py
- fbpic/particles/particles.py
- fbpic/particles/tracking/tracking.py
This simplifies the import of cuda related methods. CUDA availability is now always checked in cuda_utils and stored in the variable cuda_installed. This variable is imported at the beginning of all other cuda-related files.
> Changed cuda imports

- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/checkpoint_restart.py
- fbpic/openpmd_diag/field_diag.py
- fbpic/openpmd_diag/particle_diag.py
This pull request fixes a number of issues with the diagnostics:
- The checkpoints are now done at the end of the PIC loop
- `rho` and `J` are only brought back from spectral space if they are needed for the diagnostics
- The code does not crash anymore when trying to write into a diagnostic file that previously existed (this issue was typically due to a different number of particles in the pre-existing diagnostic)
In addition, I updated and cleaned the comments in the main step function.
> Update the diagnostics

- fbpic/boundaries/moving_window.py
When running the tests on the GPU, I realized that the new function `shift_spect_array_gpu` is causing an error when running on GPU: the power operator (`**n_move`) does not seem to work correctly.
I by-passed this strange error by simply raising to the power `n_move` by hand (since `n_move` is typically 1 or otherwise a small integer).
> Fix error with cuda power operator

- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/openpmd_diag/cuda_methods.py
- tests/test_ionization.py
When implementing the automated tests for the openPMD output with ionization (see issue #58), I realized that there was a bug in the boosted-frame output for ionization (which caused the code to crash when using it!).
The present pull request fixes this bug and implements corresponding automated tests.
Note that this pull request is to the `master` branch and not the `dev` branch. This is intentional: once the pull request is merged, I'll do a new release (`0.4.1`) that corrects this bug. I will then merge `master` into `dev` so that `dev` also has the bug fix.
> Fix and test ionization output in the boosted-frame

- docs/source/example_input/parametric_script.py
- tests/test_example_docs_scripts.py
There is a problem, when using the parmetric_script.py, if you try to start a scan with closely spaced parameters, e.g. something like:
```python
a0_list = np.linspace(1.8, 2.2, 8)
```
i.e. values that require more than single digit precision.
For the diags the script creates directories with %.1f string replacements, meaning that 1.81 and 1.84 would create the same directory, which causes problems when writing the output.
As I couldn't think of a real robust solution I just changed the precision to %.2f. This doesn't fix the problem, but makes it less likely.
> Changes precision of directory naming in parametric example script

- fbpic/particles/particles.py
Before this pull request, the particles were initialized such that, when going through the array of particles in order:
- `theta` changes the fastest (while `z` and `r` remain constant)
- then `z` changes 
- then `r` changes the slowest
However, in order to optimize cache reuse, in the current deposition and gathering, it is better to have the following order:
- `theta` changes the fastest (while `z` and `r` remain constant)
- then `r` changes 
- then `z` changes the slowest
This pull request implements the above change. 
Although this order is theoretically supposed to be more efficient (on CPU), I did not observe any significant speedup in practice. I think it still makes sense to merge this PR, as this is the most logical order for the particles to be in.
> Change order of particles at initialization

- fbpic/particles/deposition/threading_methods.py
- fbpic/particles/particles.py
This pull request introduces two changes, in order to have better scaling of the deposition routines with respect to the number of threads:
- The dimension of the global arrays (which duplicate data for each thread) are swapped (so that the thread index is the slowest index)
- The allocation of arrays that are local to each thread is removed
It turns out that on a Haswell 32-core CPU, this improves the scaling with threads quite dramatically.
> Allow better scaling of the deposition with number of threads

- fbpic/fields/spectral_transform/fourier.py
FFTW scales usually well with threads. Thus it is a good idea to use as many threads as available.
The current pull request achieves this by setting the number of threads for the FFTW to NUMBA_NUM_THREADS (which default to the available number of cores).
Note that, once this is merged with the branch `cpuprange`, then setting the number of threads through the `Simulation` interface will also set the number of threads for the FFTW.
> Use the default number of threads for FFTW

- fbpic/particles/deposition/threading_methods.py
- fbpic/particles/particles.py
This pull request implements parallel reduction after the current deposition. It speeds up the reduction by roughly a factor of 2.
Here are the timings **before** this pull request (see green curve "reduce"
)
and here is the timing **after** this pull request
> Implement parallel reduce

- fbpic/cuda_utils.py
With Python 3, this pull request avoids messages of the form
```
MPI rank 2 selected a b'Tesla K80' GPU with id 2 on node n0098.lr4
```
and replaces them instead with messages of the form
```
MPI rank 2 selected a Tesla K80 GPU with id 2 on node n0098.lr4
```
> Better printing of GPU name

- fbpic/boundaries/particle_buffer_handling.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/openpmd_diag/particle_diag.py
- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/threading_methods.py
- fbpic/particles/ionization/cuda_methods.py
- fbpic/particles/ionization/inline_functions.py
- fbpic/particles/ionization/ionizer.py
- fbpic/particles/ionization/numba_methods.py
- fbpic/particles/particles.py
- tests/test_ionization.py
In the code before this PR, the particle quantity `w` represented different things:
- For non-ionizable particles: it was the weight (i.e. number of physical particle per macroparticle) times the charge.
- For ionizable particles: it was the weight times the ionization level, times the elementary charge e. This also implied that we had to keep an additional quantity (`neutral_weight`) to store the actual number of physical particle per macroparticle, inside the `Ionizer` class.
This is confusing, and therefore the current pull request sets `w` to be the actual weight (i.e. number of physical particle per macroparticle) for both non-ionizable particles and ionizable particles. 
- For non-ionizable, this implies that `w` has to be multiplied by the charge inside the deposition kernel (this …
> `w` should be the actual particle weight

- docs/source/install/install_lawrencium.rst
- fbpic/boundaries/moving_window.py
- fbpic/particles/ionization/ionizer.py
- fbpic/particles/ionization/numba_methods.py
This pull request introduces threading in some of the used by the ionization routines.
In addition, I also bundled to small changes:
- A correction of a bug related to PR #98 (missing replacement of `neutral_weight` by `w_times_level`)
- An update of the install instructions on Lawrencium
> Add threading to ionization routines

- README.md
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
- fbpic/fields/spectral_transform/fourier.py
- fbpic/fields/spectral_transform/hankel.py
- fbpic/particles/ionization/ionizer.py
- fbpic/particles/utilities/cuda_sorting.py
This pull request incorporates by culib by:
- Updating the import statements
- Updating the installation instructions
> Switch from accelerate to pyculib

- fbpic/lpa_utils/bunch.py
- fbpic/openpmd_diag/cuda_methods.py
When changing the definition of the particle weight (see PR #98 `w` should be the actual particle weight), the functions for bunch initialization were not updated. This pull request corrects this.
In addition, I noticed that the GPU function for the boosted particle diagnostics were also not updated.
> Fix particle weight in bunch initialization and GPU boosted diagnostics

- fbpic/particles/particles.py
- fbpic/particles/utilities/cuda_sorting.py
This pull request makes the inclusive prefix sum more efficient, by avoiding that the thread handling the last particle (i.e. the rightmost particle) fills all the cells that are to its right. (see the code for a clearer picture).
This is important when a species (e.g. an electron bunch) fills only a small fraction of the plasma, since then the thread handling the rightmost particle has to fill a significant fraction of the box. But it is also important in regular simulations with guard cells, since then the thread for the rightmost particles needs to fill a significant fraction of the guard cells.
I did a few tests with a 2000x400 box with moving window (and thus guard cells) using nvprof:
- With a plasma filling the valid cells (but not the guard cells):
- Current dev branch: …
> Close #69 Optimize the `incl_prefix_sum` function when particles do not fill the grid

- fbpic/particles/particles.py
- fbpic/particles/utilities/cuda_sorting.py
The recent pull request on `prefix_sum` (PR #110) introduced a bug. 
(I thought I had successfully run the automated tests but it turns out I looked at the wrong log file.)
The bug comes up when no particles are present in a given species. In that case, the new `prefill_prefix_sum` tries to access elements of `cell_idx` which are non-existent. 
The current PR fixes this bug. I ran the automated tests on GPU and checked (and double-checked again!) that they pass successfully.
> Fixed a bug in the new `prefill_prefix_sum`

- fbpic/boundaries/cuda_methods.py
- fbpic/boundaries/moving_window.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/fields/cuda_methods.py
- fbpic/fields/spectral_transform/cuda_methods.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/gathering/cuda_methods.py
- fbpic/particles/push/cuda_methods.py
- fbpic/particles/utilities/cuda_sorting.py
This pull request removes all the function signatures for the cuda methods.
The main aim of this is to reduce the compilation time at the beginning of the simulation: I recently realized that all the functions that have signatures get compiled **when they are imported**. By contrast, the functions that do not have signatures get compiled **when they are first called**.
This means that, in the current dev branch, the deposition and gathering function for **both 1st order and 3rd order** get compiled before the simulation even starts, even though we usually only use one type of shape factor. The corresponding compilation time slows down a lot the startup time for an FBPIC GPU simulation. 
The aim of this pull request is that only the GPU functions that we do need get compiled. 
I did a few …
> Remove function signatures on GPU

- fbpic/particles/gathering/threading_methods.py
- fbpic/particles/particles.py
- fbpic/threading_utils.py
This pull request allows the 3rd order gathering to scale much better with the number of threads by avoiding the creation **for each particle** of small-sized arrays (that contain e.g. the particle shape).
Instead, these arrays are created only once for each thread (and are private to this thread), and then each thread loops over the particles in its chunk.
This uses a very similar chunking as for the deposition functions. As a consequence, I created a helper function in `threading_utils.py` which returns the array of chunk indices. (used both for the deposition, and for the 3rd gathering)
Here is the scaling with the current PR:
By contrast, here is the scaling with the current `dev` branch:
(Please disregard the curve for the Hankel transform on this last one.)
> Improve scaling of 3rd order gathering with number of threads

- fbpic/openpmd_diag/boosted_particle_diag.py
- tests/test_boosted_particle_output.py
This pull request fixes a bug with the boosted particle diagnostic (prefix_sum_shift was not taken intro account).
I also added an additional automated test, which checks that the boosted diagnostic capture all the particles that they should capture. With the current `dev` branch, this test does not pass on GPU, but it does pass on GPU with the changes from this PR.
> Close #115  Boosted particle diagnostic for GPU miss particles

- fbpic/openpmd_diag/checkpoint_restart.py
- tests/test_boosted.py
- tests/test_example_docs_scripts.py
- tests/test_ionization.py
The automated tests recently failed because the checkpoints code was not adapted to the new version of openPMD-viewer (in which `ts.iterations` is now an array, and not a list anymore).
I also took the opportunity to clean up the tests, namely:
- The tests had a lot of `os.chdir(some_directory) ... os.chdir('../')` commands. This is bad since, if a test fails in between the 2 `chdir`, then the subsequent tests will run in the directory `some_directory`, which they are not meant for. I removed the `os.chdir` and found a workaround.
- The tests of the boosted-frame NCI growth rate recently became more likely to fail. I should investigate the cause at some point, but in the meantime I just relaxed a bit the condition for the test to pass.
> Fix automated tests

- docs/source/example_input/boosted_frame_script.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/field_diag.py
This pull request modifies the branch `mpi_refactor`:
- During the diagnostics, it takes into account the fact that `rho` is never exchanged during the PIC loop.
- It corrects the exchange of J in the case where correct_currents is False (In the previous version, J was not exchange in this case, whereas it should, for the purpose of pushing the Maxwell equations)
- It prevents the use of `use_true_rho` with MPI.
> Correct MPI exchange pattern of J and rho

- README.md
- docs/source/install/install_cori_edison.rst
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
With the current dev branch, if someone tries to install FBPIC according to the documentation, they will get runtime errors because they will have numba 0.35 by default, which fails with FBPIC when trying to use threading.
This PR corrects the documentation accordingly.
> Recomend numba 0.34 in documentation

- fbpic/boundaries/boundary_communicator.py
- fbpic/lpa_utils/bunch.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/field_diag.py
The different versions of the function `add_elec_bunc` (e.g. Gaussian, uniform) were incorrect when used with MPI: in this case each proc initializes the full number of particles, and keeps them even if they are outside of the local physical domain.
This PR corrects this: each proc now retains only the particles that are within the local physical domain.
Note: in order to implement this, I needed a function that gives the zmin and zmax of the local domain. I implemented it as a method of the boundary communicator and used it in several other places in the code.
> Close #107 : Check that `add_elec` particles are within the local domain

- fbpic/threading_utils.py
- requirements.txt
With the current version of FBPIC, if a new user downloads the code and installs the latest numba (i.e. 0.35), the code will likely crash when they first try it.
This is because threading is enabled by default but fails with numba 0.35. The current `requirements.txt` will force numba 0.34 to be installed, but using `pip` instead of `conda`, and so if numba 0.35 is preinstalled with conda, it is unclear which version will be used when the user runs FBPIC.
Therefore, this pull request reverts the `requirements.txt` to its previous state, and instead disables threading for any other versions of numba than 0.34.
> Prevent threading for other version of numba than 0.34

- fbpic/boundaries/boundary_communicator.py
- fbpic/lpa_utils/bunch.py
- tests/test_space_charge.py
- tests/unautomated/test_gaussian_bunch_evolution.py
- tests/unautomated/test_space_charge_file.py
- tests/unautomated/test_space_charge_gaussian.py
This pull request corrects two short-comings of the space-charge calculation in FBPIC:
- the fact that it erased any other pre-existing field on the grid
- the fact that it was not exact when performing MPI simulations
In the new implementation, a temporary new grid, having the size of **whole physical domain** is created on the proc 0, and space-charge is calculated on this grid, using global FFT (fixes the 2nd issue). The result is then distributed to the other MPI ranks and **added** to their local grid (fixes the 1st issue).
I also added an automated test ensuring that space-charge calculation gives the same result in MPI and non-MPI simulations.
> Correct space-charge calculations for multi-proc simulation

- README.md
Hi,
I used [this](https://github.com/outsideris/slack-invite-automation#issue-token) slack app to make an invite link to our slack channels. This way users can invite themselves if they need some support from us.
It's just a suggestion, so if you want to stay in "control" reject it and I will remove the app again from our slack.
> Add Invite link for slack to README

- fbpic/particles/particles.py
As discussed in issue #129 the run time of the GPU deposit and gathering kernels can be improved by reducing the number of threads per block.
This is the minimal effort fix by just hardcoding the number of threads in the `deposit` and `gather` method to 64. 
Note, that the benchmarks in #129 show the unexpected behaviour that `deposit_rho` performs best with 48 threads per block, this is ignored in this PR.
> Set threads per block of deposition and gathering kernels to 64

- .travis.yml
- README.md
- docs/source/install/install_cori_edison.rst
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
- fbpic/fields/spectral_transform/fourier.py
- fbpic/fields/spectral_transform/mkl_fft.py
- requirements.txt
This pull requests adds the option to use the MKL FFT in FBPIC (note that the MKL library was usually automatically downloaded when installing the dependencies of FBPIC, even before this pull request). Because the performance tests are quite favorable (see below), the MKL FFT is used preferentially, and `pyfftw` is only used when MKL is not available. This also means that `pyfftw` is not, strictly speaking, a dependency of FBPIC anymore.
Regarding performance, here are the results of scaling with the number of threads, on a 24-core Intel node:
- with pyfftw:
- with MKL FFT:
The red curve (fft routines) has much lower compute cost, and also much better scaling with the number of threads in the case of MKL!
> Close #102 Experiment with MKL fft

- docs/source/advanced/profiling.rst
- docs/source/install/install_local.rst
I modified the doc to explain how to profile MPI FBPIC simulation. This can be interesting in order to see load-imbalance, how much time is spent in communications, etc. The method is quite cumbersome, but it is the best one I could think of. If you have other suggestions, don't hesitate.
I also reorganised the rest of the profiling section, so as to group it primarily by CPU/GPU rather than text-based/GUI-based.
The rendered page can be seen on this (unofficial) link:
http://www.normalesup.org/~lehe/html_fbpic/advanced/profiling.html
> Add a section on how to profile the code with MPI

- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/threading_methods.py
It seems that there was a small typo in the current deposition routines. This pull request fixes this.
Note that this bug only affects particles that are close to the axis (since it is inside an if condition with `ir_flip == -2`)
> Correct 3rd order current deposition for CPU and GPU

- fbpic/fields/spectral_transform/hankel.py
- fbpic/fields/spectral_transform/spectral_transformer.py
- tests/unautomated/test_hankel.py
The file `hankel.py` currently contains a lot of code, in order to support different types of methods to perform the discrete Hankel transform. These methods were considered in the very early days of FBPIC but were found to be inadapted, and in any case it would not be possible at all to use them with the current version of FBPIC. As a consequence, they are never used. One exception is the `QDHT` method, which is used in one of the unautomated tests, for comparison.
This pull request simplifies `hankel.py` considerably, by removing these unused methods. The definition of the `QDHT` has been moved to the corresponding test.
> Simplify the code for the Hankel transform

- fbpic/fields/spectral_transform/hankel.py
- tests/test_laser.py
- tests/test_periodic_plasma_wave.py
- tests/unautomated/test_hankel.py
This pull request modifies the calculation of the matrix that represent the Hankel transform, for the modes m>1. This is done by allowing the fields in real space to be projected onto Bessel modes (as usual) **and** one additional mode which has the same algebraic properties (for curl, grad, div) as the Bessel modes.
The following tests have been updated:
- `test_laser.py`: now tests mode m=2 in addition to m=0 and m=1
- `test_periodic_plasma_wave.py`: adds a plasma wave in the mode m=2. For now, however, this amplitude is set to 0 since the gathering has not been implemented yet.
- `test_hankel.py` now uses higher modes too.
> Generalize Hankel transform for azimuthal modes m>1

- fbpic/main.py
Oftentimes, the user needs to wait for nearly one minute for Just-In-Time compilation (esp. on GPU). Impatient users might think that the code is stuck or does not work. This PR lets them know what is happening.
Here is a typical output with this PR:
```
*** Cuda not available for the simulation.
*** Performing the simulation on CPU.
Running FBPIC on CPU with 1 proc (4 threads per proc).
Performing 200 PIC iterations:
- Just-In-Time compilation (up to one minute) ...
- Running the PIC loop
[--------------------------------------------------] 199/200, 0:00:00 left
Time taken (with compilation): 0:00:22
```
Feel free to suggest modifications. I am definitely open to making this look different.
> Print message during compilation

- fbpic/fields/fields.py
- fbpic/lpa_utils/bunch.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/field_diag.py
Right now some of the code relies explicitly on the fact that rho is never exchanged. While this works, it is not very robust (e.g. if at some point, or in some configuration, we decide to modify the exchange pattern).
Therefore, I introduced a set of flags that record whether the fields have been exchanged. I also modified the function `deposit` so that there is an option to automatically exchange the fields (even for `rho`, although it is not used right now): I think it makes things a bit clearer in the main PIC loop.
> Make the exchange of guard cells (for rho and J) more robust

- fbpic/boundaries/boundary_communicator.py
- fbpic/cuda_utils.py
- fbpic/main.py
- fbpic/mpi_utils.py
- fbpic/openpmd_diag/checkpoint_restart.py
- requirements.txt
In many use cases, FBPIC does not really require MPI (MPI is only required for parallel simulations or parallel parameter scans). Therefore, it might be good to allow FBPIC to run without mpi4y (in case some users experience issues with installing mpi4py.)
This pull request removes `mpi4py` from the requirements, and defines a dummy replacement for the places in the code where an MPI communicator is explicitly used. By default, the documentation still recommends that mpi4py be installed, since most users will not experience issues with this.
Feel free to comment/suggest alternatives, as I am not sure that this is the most elegant solution...
> Allow FBPIC to run without MPI

- fbpic/fields/spectral_transform/cuda_methods.py
- fbpic/fields/spectral_transform/hankel.py
- fbpic/fields/spectral_transform/numba_methods.py
While the fields are represented by complex numbers, the Hankel matrices are real, and therefore we can perform the matrix product on the real part and imaginary part of the fields separately. In pratice, this means that we can do a product of real matrices (`dgemm` kernel) instead of a product of complex matrices (`zgemm` kernel). As shown by the benchmarks below, it turns out that this is significantly faster, both on CPU and GPU. In addition, the conversion/copy from complex to real is negligible or unmodified.
**TODO:**
**Benchmarks (with a 2000x400 grid)**
**K80**:
|            	| Kernel name                                                                            	| Total time per iteration (ms) | 
|------------	|--------------------------------------------------------------------- …
> Make the hankel transform faster, using the fact that matrices are real

- fbpic/boundaries/field_buffer_handling.py
This is more of a suggestion: should we replace the structure `[::-1][...][::-1]` by a single indexing operation (see the code) ?
The new code feels more concise and easier to understand, to me. But it is also a matter of personal preference.
@MKirchen : Feel free to reject this PR if you disagree.
> Avoid the notation [::-1]

- fbpic/main.py
I think it is useful (both for users and developers) to know which version of FBPIC is being run. One suggestion would be to have the version printed at the beginning of the simulation, like so:
```
*** Cuda not available for the simulation.
*** Performing the simulation on CPU.
Running FBPIC 0.6.2 on CPU with 1 proc.
```
> Added version number in print message

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/cuda_methods.py
- fbpic/boundaries/field_buffer_handling.py
The MPI code was hardcoded for only 2 modes (both on CPU and GPU).
This PR generalizes it for an arbitrary number of modes. 
Note that, when doing the fields exchange, the different modes are still packed together in a single buffer array, which is thus sent in a single MPI call.
Note: this passes the automated tests. I also tested it on the (unautomated) linear plasma wakefield test, with 2 MPI processes.
> Generalize MPI code for arbitrary number of modes

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/cuda_methods.py
- fbpic/fields/cuda_methods.py
- fbpic/fields/fields.py
- fbpic/lpa_utils/laser/antenna.py
- fbpic/openpmd_diag/boosted_field_diag.py
- tests/test_periodic_plasma_wave.py
Many of the GPU kernels were hard-coded for exactly 2 azimuthal modes. 
This pull request generalizes them for an arbitrary number of modes.
This PR passes the automated tests on GPU. I also benchmarked the code on the standard 2000x400 grid, and did not see any difference in performance compared to the current `dev` branch.
> Write GPU kernels on a per-mode basis

- fbpic/boundaries/moving_window.py
When doing continuous injection in FBPIC: 
- If there is some plasma inside the initial physical box, the FBPIC continuous injection starts from the right end of that plasma.
- However, when there is no plasma in the initial box, FBPIC has to pick a z position from which to start the continuous injection. 
In the current version of the code, this initial position was effectively set at a given position inside the guard/damp cells, instead of being set at the limit of the physical box. This can cause slightly incorrect results at the beginning of the simulation, because the plasma started being injected slightly later than it should.
The current pull request fixes this by setting the initial injection position to the right of the physical box.
> Continuous plasma injection: modify the position from which injection starts

- fbpic/boundaries/boundary_communicator.py
- fbpic/cuda_utils.py
- fbpic/main.py
- fbpic/print_utils.py
General changes:
- The printing functions of main.py have been moved to a new file print_utils.py (makes main.py a little bit cleaner)
Enhancements in the printing at the beginning of the simulation:
- The simulation object takes a new argument "simulation_info" that specifies the level of detail for printing simulation information (0 = no information, 1 = basic information (default), 2 = detailed information, such as n_order/n_guard/exchange_period...)
- Prints version of FBPIC after the initialization of the simulation object
- Slight refactoring of the info about the computing architecture used: CPU / GPU / MPI / threads per process
Changes to the progress bar:
- During the first iteration a warning about the JIT compilation overhead is shown instead of the progress bar
- The first …
> Refactored printing of simulation setup and the progress bar

- fbpic/boundaries/boundary_communicator.py
- fbpic/fields/fields.py
- fbpic/main.py
In the current dev branch, we perform 16 Hankel transform and 16 Fourier transform per azimuthal mode and per iteration. Within those 16 transforms, 12 transforms are done because we do a `spect2interp` and `interp2spect` of the fields E and B (2 * 2 fields * 3 components).
The reason for performing these back-and-forth transformations is that we have to perform some operations on the fields in spectral space (Maxwell push) and some operations in real space (MPI exchanges and damping of the open boundaries). 
However, because the MPI exchanges and damping of the open boundaries is purely along z, updating the spectral fields can be done only by a succession an inverse and forward Fourier transform (no Hankel transform involved). Then updating the fields in interpolation space requires an …
> Reduce the number of Hankel transforms per iteration

- fbpic/threading_utils.py
The newest version of numba (0.36) works fine with FBPIC multi-threading.
The restriction in threading_utils.py has been modified such that numba 0.34 and 0.36 can be used together with multi-threading. 
When numba 0.34 or 0.36 are not installed, the user is recommended to install numba 0.34 (as 0.36 is not yet included in the official anaconda channel)
Note: We should remove this restriction completely in the future and just require a minimum numba version.
> Allow CPU multi-threading with numba 0.36

- fbpic/openpmd_diag/boosted_particle_diag.py
When doing the particle boosted frame diagnostic, the code gets a thin slice of particles on GPU, which is then brought on CPU for further selection.
The bounds check when getting this slice was not done carefully enough, and were resulting in an out-of-bounds. This happened specifically with Galilean frame because `pref_sum_shift` (which measures the shift between the position of the current grid and of the grid at the time of the last sort) can take larger values in this case (typically pref_sum_shift=2 in this case).
> Close #166 Error with BoostedParticleDiagnostics when galilean frame is used on GPU

- .travis.yml
- README.md
- docs/source/install/install_cori_edison.rst
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
Now that numba 0.36 is available on the standard conda channel, we should not recommend numba 0.34 anymore.
> Use the new version of numba (0.36)

- .travis.yml
- fbpic/lpa_utils/bunch.py
After PR #170, I realized that the automated tests were using numba 0.35 instead of numba 0.36. Upon further investigation, it seems that this is because we were using Miniconda 2 (I do not fully understand why numba 0.36 is not automatically installed in this case).
For this reason, I switched to Miniconda 3, and checked that numba 0.36 is indeed used in automated tests. In addition, I also switched the Python3 tests from Python 3.5 to Python 3.6.
An unexpected consequence of Miniconda 3 is that, with Python 2, it installs numpy 1.10 instead of 1.13. This caused some bugs because the `random.normal` (which is used in bunch.py) does not support being passed a standard deviation of 0. Therefore, I also modified `bunch.py` so that it never passes a standard deviation of 0 to …
> Use numba 0.36 in automated tests

- fbpic/lpa_utils/laser/__init__.py
- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_laser.py
This pull request adds the Laguerre-Gaussian profile in FBPIC (This is a follow up on #150). 
These profiles can be used as building blocks for other laser profiles (e.g. radially polarized pulse, quasi-flat top pulses, etc.). Another pull request will introduce the overloaded + operator for laser profiles, so that Laguerre-Gaussian profiles can be easily combined.
All the formulas used in the implementation of this new profile are from Siegman, Lasers (1986). 
I update the automated tests, so that they now check the propagation of Laguerre-Gaussian pulse of order 0, 1 (i.e. the laser spot is *not* cylindrically symmetric.)
> Add Laguerre-Gaussian profiles

- fbpic/boundaries/particle_buffer_handling.py
For some reason, the function `merge_buffers_to_particles` is very slow. For instance, in the usual 2000x400 benchmark with linear shape factors, the cost of this function can be of the same order as the gathering and deposition functions!
This is very surprising since the function `split_particles_to_buffers` is almost identical, but takes 20x less time per call!
In any case, I now replaced the function `merge_buffers_to_particles` by a set of simpler functions. The time taken by these different functions is now negligible. For instance, on the 2000x400 benchmark with a GTX 1080 Ti GPU, the `dev` branch takes 56 s while this PR takes 51 s.
> Replace the function `merge_buffers_to_particles` by a faster set of function

- fbpic/fields/spectral_transform/mkl_fft.py
- fbpic/threading_utils.py
- setup.py
Although Windows is not the priority for fbpic, it might be good to have the code work there too, if it requires not too much effort. 
With the few changes of this PR, I was able to run the standard LWFA example. Note that I had to disable threading (I was getting an exception from Numba during JIT compilation, saying that Windows is not supported yet).
> Close #176 MKL FFT errors on Windows

- fbpic/lpa_utils/bunch.py
- fbpic/main.py
- fbpic/openpmd_diag/checkpoint_restart.py
This is a reimplementation of PR #162, decided after off-line discussion with @MKirchen.
From the original PR:
> The checkpoint / restart feature was broken:
> 
> - In load_species the weights were multiplied by the charge q. This should not be done anymore.
> - If a diag_period was at the same time as a checkpoint_period, a wrong diagnostic was written at the first step (i_step == 0) after the restart (wrong charge/currents). With this PR, a check is  performed based on a new attribute (is_restarted) of the Simulation object.
The current PR fixes the second issue by swapping the order of the diagnostics and the particle exchange (particle exchange first, then diagnostics). Since the particle exchange phase is always followed by a deposition of charge (including immediately after a …
> Fix checkpoints

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/moving_window.py
- fbpic/lpa_utils/bunch.py
- fbpic/lpa_utils/laser/antenna_injection.py
- fbpic/lpa_utils/laser/direct_injection.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/field_diag.py
The code related to the size/boundaries of local and global domains is currently somewhat messy:
- There are many redundant variables stored inside the `BoundaryCommunicator` object (`Nz_domain_procs`, `Nz_domain`, `Nz_enlarged_procs`, `Nz_enlarged`, `Nz`). Also, it is not always clear whether these quantities include guard cells and/or damp cells, and whether they apply to the local or global domain.
- The position of local/global boundaries are recalculated several times in different places of the codes. This is redundant, and also complicates/lengthens parts of the code that are not directly related to domain decomposition.
- The two above remarks make it hard to change the code, if at some point we want to change the domain decomposition (e.g. to have better load-balancing)
Instead, …
> Refactor the calculation of domain boundaries

- fbpic/lpa_utils/laser/__init__.py
- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_laser.py
**Please merge #172 first**
This pull request introduces the overloaded + operator for laser profiles. This is done by:
- Having a base class, which defines the `__add__` method, and from which all laser classes should inherit.
- Defining a new type of profile (`SummedProfile`) which is returned by the `__add__`method, and simply calls each of the profiles of the sum, and then adds the resulting fields.
The automated tests have been updated to take this profile into account.
> [WIP] Overload the + operator for laser profiles

- fbpic/boundaries/boundary_communicator.py
- fbpic/lpa_utils/bunch.py
- fbpic/lpa_utils/laser/direct_injection.py
PR #150 introduced a more general and self-consistent way of initializing the laser, but it also stopped initializing the fields in the damp cells. (With PR #150, the field in the damp cells is zero, whereas it was not the case before.)
However, initializing the fields to 0 in the damp cells creates a sharp discontinuity between the last physical cell and the first damp cell. This discontinuity may produce low-amplitude spurious fields, when evolved with the Maxwell solver. For this reason, the current PR modifies the initialization of the laser so that the damp cells are initialized as well. As can be seen below, this removes the low-amplitude spurious field. (Note that the colorscale is strongly saturated for the laser pulse itself, so as to show the low-amplitude spurious field.)
In …
> Initialize laser field in the damp cells

- fbpic/particles/gathering/cuda_methods.py
- fbpic/particles/gathering/inline_functions.py
- fbpic/particles/gathering/threading_methods.py
In the code for field gathering, there is a lot of code duplication:
- the gathering and weighting of E is very similar to gathering and weighting of B
- the gathering for mode 0 is very similar to the gathering for mode 1
- the code for CPU is very similar to the code for GPU
For this reason, I wrote a single function that does the gathering and weighting for an arbitrary field (E or B), arbitrary mode, and for both CPU and GPU (with one version for linear shape and one version cubic shape). This elementary function is then used in the CPU and GPU kernels (it is compiled either `cuda` or `numba` ; a similar approach was used in the ionization code.)
Also, I got rid of the `iz` and `ir` arrays for cubic deposition (as they are very easy to recalculate on the fly, just before accessing the …
> Reduce duplication in gathering kernels by using more elementary functions

- fbpic/boundaries/particle_buffer_handling.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/particles.py
- fbpic/particles/utilities/cuda_sorting.py
This pull request is a proposition to slightly change the way in which we sort the particles on the GPU, in order to simplify the deposition kernels.
More precisely, in the current `dev` branch, the particles are sorted according to the index of their lower grid point in z and r as shown here with tuples of `(iz_lower, ir_lower)`. (In the code, these tuples are actually translated into a single index `ir_lower + Nr*iz_lower`, but this is a detail.)
Notice that the particles that are below the first radial grid cell do not have a lower grid point in r, and so, **currently**, they are put in the same "bag" as the particles that are inbetween the first radial grid point and second radial grid point. (The same problem does not occur in `z` because of the periodicity in z.)
Then, the …
> Close #139 Simplify/optimize the code for current deposition on GPU

- fbpic/particles/deposition/threading_methods.py
In the latest release of fbpic, there is a bug caused by PR #137 ("Simplify current deposition on CPU and generalize it for multi-mode") : when performing charge/current deposition, particles that are at high radius can potentially do out-of-bound array access. 
This only affects the code on CPU, but can have drastic effect, as in the typical simulations of laser-wakefield below: (My guess is that the out-of-bound access can result in accessing array indices that normally correspond to low-radius, hence the observed spurious high density close to the axis)
- **fbpic 0.7.0, on CPU**:
- **fbpic 0.7.0, on GPU**:
The current pull request fixes this:
- **Current PR, on CPU**
> Prevent out-of-bound in CPU charge/current deposition

- fbpic/openpmd_diag/checkpoint_restart.py
PR #179 introduced the the new variable `_zmin_global_domain`. This variable needs to be updated when performing a restart. 
In the current `dev` branch, this is not the case. As a result, the moving window and continuous injection of plasma will behave strangely, as in this example (with a restart at iteration 100, and continuous injection of a plasma with a density ramp):
On the other hand, this PR updates `_zmin_global_domain` (by calling the function `shift_global_domain_positions`), and results in correct injection:
> Close #190 Restarting is buggy because `_zmin_global_domain` needs to be set

- fbpic/particles/deposition/cuda_methods_one_mode.py
- fbpic/particles/particles.py
This implements the deposition for arbitrary number of modes.
This duplicates the functions for 2 modes (i.e. the functions for 2 modes have been kept in the code, since they are, in general, faster than the functions for arbitrary number of modes.)
I tested the new routines, and they work as expected.
For future reference, here is the performance for the usual 2000x400 test (with 2 azimuthal modes):
- Using the usual functions for 2 modes
deposit_J_gpu_linear: 17.0 ms / iteration
deposit_rho_gpu_linear: 5.6ms / iteration
deposit_J_gpu_cubic: 97.9 ms / iteration
deposit_rho_gpu_cubic: 22.7 ms / iteration
- Forcing the use of the per-mode kernel (thus these kernels are called twice per iteration - once per azimuthal mode):
(2x) deposit_J_gpu_linear_one_mode: 22.0 ms / iteration
(2x) …
> Implement deposition for arbitrary number of modes, on GPU

- fbpic/particles/gathering/cuda_methods_one_mode.py
- fbpic/particles/gathering/threading_methods_one_mode.py
- fbpic/particles/particles.py
- tests/test_periodic_plasma_wave.py
This implements the gathering functions for an arbitrary number of modes. Because the per-mode functions are usually slower than the functions for 2 modes, I duplicated the kernels. 
Also, when calling the gathering function for 2 modes, we overwrite the arrays of fields on the particles (these arrays typically contain the fields from the previous iteration, and so they *have* to be overwritten). However, when calling the per-mode kernel for each mode, we cannot overwrite the values anymore (otherwise calling the function for mode m=1 would overwrite for mode m=0). Therefore, I had to add a small kernel that sets the arrays of fields on the macroparticles to 0, and then the per-mode kernels *add* the value from each mode instead of overwriting.
I tested this and made sure that the new …
> Implement gathering for arbitrary number of modes, on CPU and GPU

- fbpic/openpmd_diag/generic_diag.py
This writes the FBPIC version in the openPMD file. This can be important, when retrieving old data, and for reproducibility.
> Write FBPIC version number in openPMD file

- tests/test_periodic_plasma_wave.py
This modification was previously made on the `cross_deposition` branch.
Because this change is not specific to the `cross_deposition`, I implement it separately here.
Note that, because we currently do not have a charge-conserving algorithm for parallel simulations, this test fails when run in parallel (but is successful when run in serial).
> Modify test_periodic_plasma so that it can be run in parallel

- tests/test_linear_wakefield.py
- tests/unautomated/test_linear_wakefield.py
I modified the linear laser-wakefield test so that:
- It can test the wakefield generated in different azimuthal modes (including m=2)
- It checks the accuracy of the wakefield (profile and amplitude) automatically
- The test runs for each push (but only using m=0, in this case, for faster tests)
Regarding the first point (wakefield generated in different azimuthal modes), I modified the script so that it tests the following situations: (For each situation, the 3D image shows the laser (red-orange) and Ez in the wakefield (blue-yellow).)
- **Donut-shaped laser, polarized along theta**: in this case, both the laser and the wakefield are donut-shaped, and entirely contained in mode m=0. So only one azimuthal mode is used in the calculation. (This is the case which is automatically tested …
> Automate and generalize the test for linear laser-wakefield

- fbpic/openpmd_diag/generic_diag.py
It turns out that, if the user passes a float for `period`, then diagnostics are sometimes never written.
(This is because the code checks `iteration % period == 0` in order to determine whether to write a file at this iteration. If period is a float, then this operation is still defined. If `period` is nearly equal to an integer but not exactly (due to e.g. machine precision), then the above condition is sometimes never met.)
> Impose that the period of the diagnostics is an int

- fbpic/utils/threading.py
I tested the code with numba 0.37 (for the moment, only available in the `numba` channel) and everything seems to run fine. Therefore, I think we can allow it in the `threading.py`.
> Allow numba 0.37 for threading

- fbpic/boundaries/moving_window.py
Right now, the shifting of the moving window is performed in spectral space.
The moving window functions still have the option of performing the shift in interpolation space. However, **this is misleading**: because of the way in which the `step` function is written, the shifted fields in interpolation space will be overwritten by the (unshifted) fields in spectral space.  So, using the shift in interpolation space will result, in practice, in no shift at all.
For this reason, I propose that we remove the option of shifting the fields in interpolation space.
> Remove shifting of moving window in interpolation space

- fbpic/boundaries/moving_window.py
As discussed off-line, the moving window used to be only valid for one direction.
This pull request corrects the code, so that the moving window can work in both directions.
I successfully tested this both on CPU and GPU.
> Generalize moving window for both direction

- .travis.yml
- setup.py
- tests/test_boosted.py
- tests/test_continuous_injection.py
- tests/test_external_fields.py
- tests/test_laser.py
- tests/test_laser_antenna.py
- tests/test_linear_wakefield.py
- tests/test_periodic_plasma_wave.py
- tests/test_uniform_rho_deposition.py
In the current `dev` version, `matplotlib` is required in order to run the tests. 
However, it is unnecessary since the tests automatically check the results, instead of producing plots. In addition, on some plateforms, matplotlib can be difficult to install. Therefore, I suggest that we remove matplotlib from the requirements of the automated tests.
With this PR, matplotlib is only imported when the flag `show` is `True`. This typically happens when running the tests directly with python (e.g. `python test_boosted.py`) but not when running the tests through `python setup.py test`.
> Remove matplotlib requirements for automated tests

- docs/source/example_input/boosted_frame_script.py
- fbpic/fields/fields.py
- fbpic/main.py
In principle `use_true_rho` could be used in parallel if the charge density is properly exchanged. This can be advantageous, e.g. to run boosted-frame simulations with the Galilean method and multiple MPI.
This PR implements the corresponding changes:
- Instead of preventing `use_true_rho` whenever multiple MPI ranks are used, this only prevents in the case where both current correction and multiple MPI ranks are used. (Because in this case, the exchange requirements for rho are contradictory.)
- As an additional safeguard measure, this PR checks that the fields rho and J have been exchanged, just before pusing E and B. This check is only done when using multiple MPI  ranks.
- The guard cells of rho are now exchanged whenever rho is deposited.
> Allow the use of `use_true_rho` in parallel

- fbpic/boundaries/particle_buffer_handling.py
- fbpic/particles/elementary_process/compton/compton.py
- fbpic/particles/elementary_process/ionization/ionizer.py
- fbpic/utils/printing.py
In the current `dev` branch, for multi-GPU simulations, the simulation just hangs when one GPU reaches out-of-memory. This is obviously a waste, when using allocated resources on a cluster.
The current pull request modifies the code, so that `fbpic` catches the out-of-memory error and calls MPI Abort, so as to stop the simulation. In addition, a message is printed, which typically looks like this:
```
ERROR: GPU reached OUT_OF_MEMORY on MPI rank 11
(Error occured in function add_buffers_gpu)
```
Regarding the implementation: this is done by creating a decorator which catches the out-of-memory error in the decorated function. This decorator is then added to a couple of functions in fbpic which are likely to lead to out-of-memory (basically functions that create new particle arrays).
If an …
> Close #200: Better error handling when reaching out-of-memory

- fbpic/boundaries/moving_window.py
- fbpic/fields/fields.py
- fbpic/main.py
Each instance of the `Interpolation` class keeps a copy of the `1d` arrays `z` and `r`. This is not very good practice, since these arrays can be recomputed from other attributes of the `Interpolation` class (and thus constitute a case of duplication of information). In addition, this duplication is annoying because the full array `z` needs to be updated whenever the moving window moves, whenever the Galilean grid shifts, or whenever there is a restart (we don't even do the last one! - and thus the current code is buggy from that point of view)
In order to avoid these issues, I removed the array `z` and `r` from the `Interpolation`. However, since a few (rare) parts of the code need these arrays, I included two functions that compute them on the fly, from the other known attributes of the …
> Remove the arrays `z` and `r` from the `Interpolation` class

- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/cuda_methods_one_mode.py
- tests/test_cpu_gpu_deposition.py
In [PR #182](https://github.com/fbpic/fbpic/pull/182), the calculation of the particle index (for sorting on the GPU) was switched from using the lower index (with `math.floor`) to using the upper index (with `math.ceil`).
Then when doing the charge/current deposition, this index is used in order to extract the radial and longitudinal index at which the particles should deposit their charge/current. However, when computing the shape factors, the radial and longitudinal index are **recomputed independently**. In theory, this could lead to discrepancies, unless these radial and longitudinal indices are computed **exactly in the same way** in the sorting algorithm and in the shape factors.
Right now, the indices **in the shape factors** are computed use the `math.floor` function. This will …
> Correct round-off errors in GPU deposition

- fbpic/particles/particles.py
Initializing macroparticles with zero weight can be extremely inefficient - especially in cases where the `dens_func` for a given species is non-zero only in a restricted area of space.
This PR prevents the code from initializing these useless macroparticles (since they do not contribute to the physics). 
Here is the results of a small test, where the `dens_func` is 0 outside of the range 25 microns - 40 microns. Note that this PR is compatible with the moving window (in this test, the initial box spanned over the range -10 microns - 30 microns).
One disadvantage of this PR is that the code will refuse to create "tracer" particles (a.k.a. "test" particles), which, by definition, have zero weight. However, since use cases for tracer particles are (in my mind) rather rare, I think that the …
> Avoid initializing macroparticles with zero weight

- fbpic/openpmd_diag/checkpoint_restart.py
- tests/test_example_docs_scripts.py
This pull request modifies the automated test that runs the example file `lwfa_script.py`, so as to make a more thorough check of the restarted simulation:
- The script first runs this script for `2*N_step` steps (with `N_step=200`).
- A new simulation is then run from a checkpoint file at `N_step` running up to `2*N_step` (i.e. the last N_step from the previous simulation are run again)
- Then the fields in the openPMD files of the 2 simulations are automatically compared.
In addition, the file for this automated test has been refactored to avoid duplications:
- Since the above test is performed for 1 MPI proc and then for 2 MPI procs, I wrote a generic function that takes the number of MPI procs as argument (the function used to be duplicated for 1 and 2 MPI procs)
- The code used to …
> Close #222 Add automated test that check the accuracy of a restarted simulation

- fbpic/lpa_utils/bunch.py
- fbpic/main.py
- fbpic/particles/injection/__init__.py
- fbpic/particles/injection/ballistic_before_plane.py
- fbpic/particles/particles.py
- fbpic/particles/push/cuda_methods.py
- fbpic/particles/push/numba_methods.py
- tests/test_beam_focusing.py
This add the ability to inject relativistic particles through a plane that has a fixed position in the lab frame (as a consequence the plane moves in the boosted frame). More precisely, the particles will have a ballistic motion before the plane (i.e. they do not feel the fields) and will have a non-ballistic motion after the plane. These particles still deposit their charge and currents both before and after the plane.
The API of the functions that inject a bunch have been modified so that the user can pass the position of the plane (in the lab frame).
This implementation also introduces a generic `injector` attributes for any instance of `Particles`. Right now, the `BallisticBeforePlane` is the only possible injector, but in the future, I would like to refactor the code that does …
> Close #147 Add injection of relativistic particles through a plane

- fbpic/__init__.py
- fbpic/fields/fields.py
- fbpic/main.py
- fbpic/particles/particles.py
- fbpic/utils/mpi.py
- fbpic/utils/threading.py
Users can sometimes make the mistake of creating `dens_func` with negative densities. It is nice to let them know about this (with a proper warning), and to avoid initializing the corresponding particles.
In the case of a negative density, the user will see the following printed message:
```
UserWarning: /Users/rlehe/Desktop/fbpic/fbpic/main.py:205:
Cuda not available for the simulation.
Performing the simulation on CPU.
FBPIC (0.8.0)
Running on CPU (4 threads per process) 
Initializing laser pulse on the mesh...
Done.
|█                                  | 7/200, calc. ETA..., 71 ms/step
UserWarning: /Users/rlehe/Desktop/fbpic/fbpic/particles/particles.py:181:
The specified particle density returned negative densities.
No particles were generated in areas of negative density.
Please check …
```
> Better message warnings, including when generating negative particle densities

- docs/source/api_reference/simulation.rst
- fbpic/boundaries/boundary_communicator.py
- fbpic/lpa_utils/bunch.py
- fbpic/main.py
- tests/test_compton.py
In the current `dev` branch, the only way to initialize a new species is by using the `Particles` object directly.
However, there are many pitfalls when using this object directly (esp. when doing boosted-frame simulation, or multi-CPU/multi-GPU simulations). 
This PR solves this issue by creating a helper function `add_new_species`, which takes automatically takes care of these issues.
Note that this helper function is a temporary, backward-compatible patch: in the future (`fbpic 1.0`) we hope to have a better (but non-backward-compatible) API.
> Add new way to initialize particles

- fbpic/boundaries/boundary_communicator.py
- fbpic/main.py
Closes #204 
I increased the default values for n_damp and n_guard from 30 to 64.
I've chosen 64 (and not 50 as written in the Issue) because it is a power of 2.
Reasons to increase the values although this might give performance degradation for very small simulation box sizes:
**Damping region**
With 30 n_damp cells, only 10 cells are actually performing the damping whereas the remaining 2/3 of the cells are set to 1. I think a damping region of only 30 is a little bit to small as a default value and increasing this will give robustness in cases where this could matter. However, I have no evidence that the current setting can cause problems. If we change the default value to 64 it might also be beneficial to enlarge the real damping area to 1/2 of n_damp instead of only 1/3 of n_damp. In …
> Increase default values for damping and guard region size

- docs/source/api_reference/api_reference.rst
- docs/source/api_reference/particles.rst
- docs/source/api_reference/simulation.rst
- docs/source/example_input/boosted_frame_script.py
- docs/source/example_input/ionization_script.py
- docs/source/example_input/lwfa_script.py
- docs/source/how_to_run.rst
- fbpic/main.py
- fbpic/particles/elementary_process/ionization/read_atomic_data.py
- fbpic/particles/particles.py
- tests/test_example_docs_scripts.py
- tests/test_ionization.py
This PR update and expands the documentation by:
- Encouraging the user to use the new function `add_new_species`
- Adding a section on the `Particles` object, which includes the documentation of the `make_ionizable` method. Note that the `__init__` method of the `Particles` object is **not** documented.
- Adding a new downloadable script for ionization simulation. Note that `add_new_species` makes this script much simpler than it would have been in the previous fbpic release. This script is now also automatically tested in `test_example_doc_scripts.py`. Note that `add_new_species` is now also used in the automated test `test_ionization.py`.
The modified documentation can be seen here: http://www.normalesup.org/~lehe/html_fbpic/
This PR also makes a number of arguments of the `Simulation` …
> Close #187 Document ionization module and add an example script 

- fbpic/lpa_utils/boosted_frame.py
- fbpic/lpa_utils/bunch.py
- fbpic/main.py
- fbpic/particles/elementary_process/cuda_numba_utils.py
- tests/test_beam_focusing.py
- tests/test_compton.py
This PR fixes a few bugs in the bunch initialization:
- for the function `add_elec_bunch` (i.e. uniform bunch), `p_zmin` and `p_zmax` were not properly transformed in boosted-frame simulations. This is fixed by taking into account the `beta` of the plasma inside `add_new_species`.
- for the function `add_elec_bunch_from_arrays`, the particles were selected in the local domain *before* they were Lorentz-transformed. Because the local domain boundaries are expressed in the boosted frame, this was incorrect. In order to fix this bug, I had to fix the function `boost_particles`, so that it can take arrays as inputs (instead of taking a `Particles` object)
In addition, the method `add_new_species` is now also used when creating the particles from arrays. More precisely, an empty species is …
> Fix bunch initialization

- fbpic/boundaries/moving_window.py
- fbpic/main.py
- fbpic/openpmd_diag/checkpoint_restart.py
- fbpic/particles/injection/continuous_injection.py
In the current `dev` branch, the positions that keep track of plasma injection are initialized when `set_moving_window` is called.
However, this is not ideal, since it relies on `set_moving_window` being called after all continuously-injected species are created. With `add_new_species`, users might inadvertently create new species after the moving window is set.
Therefore, this PR moves the initialization of these positions at the beginning of `step`. Note that, if `step` is called multiple times, these variables are not reinitialized (because of the `if self.z_inject is None` condition).
On the other hand, in the rare case where a user calls `step`, then does a restart, and then calls `step` again, these variables to need to be reinitialized. I added a new method …
> Initialize injection positions at the beginning of step

- fbpic/boundaries/moving_window.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/fields/fields.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/particles/particles.py
When shifting the moving window, we avoid having to sort the particles again (as long as the particles are not pushed by the particle pusher) by setting the `prefix_sum_shift` variable, which keeps track of the number of cells that the moving window moved, since the last time that the particles were sorted.
Currently, this is a single attribute for all particle species. However, this assumes that all species are always sorted at the same time. This is not necessarily the case, e.g. because some species could be involved in boosted-diagnostics (which involve particle sorting in order to extract particle slices) whereas others are not.
For this reason, `prefix_sum_shift` is now a per-species attribute.
I successfully ran the automated tests on GPU, for this PR.
> Close #117 Each species should have its own `prefix_sum_shift`

- docs/source/example_input/ionization_script.py
- fbpic/openpmd_diag/checkpoint_restart.py
- tests/test_example_docs_scripts.py
The restart mechanism was incorrect for ionizable species, because the associated quantities (ionization level, weight multiplied by the level) were not set during the restart.
This PR fixes the issue, and adds an automated test that restart an ionization simulation and checks that the results are *close* to those of a simulation without restart. Note that, because of the randomness of the ionization (which is *not* controlled by the `numpy` random seed, but instead by some seed inside `numba`), the restarted simulation will not give the same results, and the tolerance with which the fields are checked must be adapted.
> Close #213  Restart does not work for ionizable species

- docs/source/advanced/boosted_frame.rst
- docs/source/advanced/parameter_scans.rst
- docs/source/advanced/profiling.rst
- docs/source/example_input/boosted_frame_script.py
- fbpic/main.py
This adds various tips in the documentation, mainly based on feedback from users:
- Mentions that the number of particles should be increased when increasing the number of azimuthal modes.
- Mentions that boosted-frame simulations should include ions, and that it is good to check the convergence with lower gamma.
- Insists on using the parameter ``use_all_mpi_ranks`` when doing parameter scans (easily overlooked in the documentation)
- Mentions how to profile multi-GPU code
- Prevents the timestep from being too big in the example boosted-frame simulation.
The updated documentation can be seen here: http://www.normalesup.org/~lehe/html_fbpic/
> Add various tips in the documentation

- README.md
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
The current installation instructions recommend
```
conda install -c numba pyculib
```
It turns out that this automatically installs cuda **version 9.1** (as a package named `cudatoolkit`). Because this is the most recent version of cuda, most users will have a driver that **does not** support cuda 9.1, and fbpic will typically fail to run, with the following error:
```
pyculib.blas.binding.CuBLASError: CUBLAS_STATUS_NOT_INITIALIZED
```
By contrast, when typing
```
cuda install pyculib
```
the installed version of cuda is 8.0. This is much less likely to cause bugs due to (relatively) old driver.
As a consequence, this PR updates the instructions to remove `-c numba`.
> Install pyculib from standard conda channel

- fbpic/boundaries/boundary_communicator.py
- fbpic/fields/utility_methods.py
- fbpic/main.py
With this PR the stencil extent for simulations using the Galilean scheme is calculated correctly. In contrast to lab frame simulation where the extent is calculated from the C and S coefficients in the field equation, in the Galilean scheme Theta^2*C and Theta^2*S need to be used.
> Correctly calculate the stencil extent in the Galilean scheme

- fbpic/boundaries/boundary_communicator.py
- fbpic/fields/fields.py
In the `dev` branch, the `InterpolationGrid` requires the array `z` to be passed, but this array is in fact only used in order to calculate `dz` and `zmin`,`zmax`.
Therefore it is a bit weird/ugly to pass the full `z` array. This PR modifies the API of `InterpolationGrid` to fix this.
> Simplify the API of the InterpolationGrid

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/field_buffer_handling.py
This PR is more of a suggestion ; feel free to reject it.
The aim is to reduce duplication in the code for the MPI exchanges. This is done (mainly) by using dictionaries that point to the different types of MPI buffers, instead of using `if` conditions which explicitly refer to the buffer in each case.
Also, there is now a separate buffer for each of the exchanges that are done (replace B, replace E, add J, add rho). In the future, this could be useful in order to make these exchanges asynchronous, and overlap them. There is no buffer anymore for the exchanges that are not done in the code (replacing a scalar).
I successfully tested this with 2 MPI, using the `test_linear_wakefield.py` with `n_order=32` in the following configurations:
- on CPU
- on GPU without GPU-direct
- on GPU with …
> Simplify MPI code, and use separate buffers for E and B exchange

- docs/source/api_reference/lpa_utilities/laser.rst
- docs/source/api_reference/lpa_utilities/laser_profiles/flattened.rst
- docs/source/api_reference/lpa_utilities/laser_profiles/gaussian.rst
- docs/source/api_reference/lpa_utilities/laser_profiles/laguerre.rst
- fbpic/lpa_utils/laser/__init__.py
- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_flattenedgauss_laser.py
- tests/test_laser.py
This adds a laser profile which is flattened in the near-field and has rings in the far-field. The advantage of this profile is that it has a fully analytical expression for any `z` and `t` (contrary to an exact flat-top profile).
In addition, the documentation for laser profiles has been slightly modified, in order to list the different available laser profiles, and have one page per profile, as this makes it more readable ; here is a preview: http://www.normalesup.org/~lehe/html_fbpic/api_reference/lpa_utilities/laser.html#laser-profiles
TODO
> Add laser profile for flattened Gaussian laser

- fbpic/lpa_utils/laser/laser_profiles.py
The laser profiles typically use complex numbers to simplify the math ; however the `E_field` function only returns the real part of that complex number.
Right now, the complex number that are used are of the form
```
complex_profile = exp( i k (ct - z) + Z )
```
where `Z` is a complex number which groups other terms (wave front curvature, etc.)
However, because we only use the real part of this, we could also use the complex conjugate
```
complex_profile = exp( i k (z - ct) + Z* )
```
and still get the same result.
In the end, using the first or the second expression is a matter of convention. However, the first expression is somewhat confusing because we use the convention  `exp( i k (z - ct) )` in the derivations of the FBPIC paper. 
Also, in the case of the laser envelope model, the …
> Switch complex convention for definition of laser profiles

- docs/source/api_reference/lpa_utilities/laser.rst
- docs/source/api_reference/lpa_utilities/laser_profiles/donut_laguerre.rst
- fbpic/lpa_utils/laser/__init__.py
- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_laser.py
This pull request adds a new type of laser profile: the donut-like Laguerre-Gauss modes.
These modes have a cork-screw phase pattern and a donut-like intensity pattern.
While these modes can in principle be constructed from the regular Laguerre-Gauss modes, it is somewhat error-prone (esp. for large m). And in practice, this is a common enough laser profile that several users might want to use it.
This PR also adds a few checks for the regular Laguerre-Gauss modes, so as to prevent users from using negative`m`.
> Close #253 Implement donut-like Laguerre-Gauss modes

- fbpic/lpa_utils/bunch.py
- fbpic/lpa_utils/laser/direct_injection.py
It sometimes annoying/confusing that each MPI rank print 
```
Initializing laser pulse on the mesh...
Done.
```
This PR fixes the issue.
> Have only MPI rank 0 print information on laser/beam initialization

- fbpic/boundaries/moving_window.py
- tests/test_laser_envelope.py
This PR follows the PR 255 since it uses the GPU methods added there.
It allows for the use of a moving window while using the envelope approximation, with both normal and GPU computations. A test for this has also been added in test_laser_envelope.py
Of note: The accuracy of test_laser_envelope.py in regards to the amplitude (for moving_window and periodic) was inconsistent with Nz (even when increasing Nz) and often got beyond 5e-3, I increased it to 6e-3 for now to pass the tests.
> Implements moving windows for the envelope

- fbpic/lpa_utils/laser/direct_injection.py
- fbpic/lpa_utils/laser/laser.py
- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_laser_antenna.py
This PR depends on PR #259.
It allows each laser profile to propagate in the forward or backward direction.
For the backward direction, the formulas are obtained by basically applying the transformation `z => -z` in the existing formulas.
In addition, all laser profiles now need to have the attributes `forward_propagating` and `propag_direction`. The parent class `LaserProfile` has an `__init__` method that initializes these variables. 
Then these attributes are used in the `add_laser_pulse` method. Therefore the argument `fw_propagating` is not needed anymore, and was removed. Technically, this breaks backward compatibility ; however, I doubt that anyone was using `fw_propagating=False` with this (relatively new) function, and thus I think it's fine. @MKirchen Any opinion on this?
> Allow laser profiles to propagate forward or backward

- fbpic/lpa_utils/laser/antenna_injection.py
- fbpic/lpa_utils/laser/laser.py
- tests/test_laser_antenna.py
Having a moving antenna can be useful in cases where e.g. a counterpropagating laser needs to be emitted in a moving window.
This PR implements the moving antenna ; for the moment this is incompatible with the boosted frame. (The boosted frame formulas used for the antenna assume that the antenna does not move in the lab frame.)
Note that I allowed the antenna to deposit charge/current in the damp cells. This is because users will typically put the antenna at `zmax` and with the same velocity as the moving window. However, because the moving window moves only once per timestep, and the antenna moves at every half timestep, this means that the antenna typically gets out of the physical box (on a length scale of half a cell).
> Implement moving antenna

- fbpic/boundaries/field_buffer_handling.py
PR #247 introduced a bug in the MPI exchange of `rho`, when running on GPU: after the MPI exchanges (on CPU), the MPI buffers were not properly copied to GPU.
For instance, here is the rho diagnostic for the `test_linear_wakefield.py` run with 2 MPI rank and the `dev` branch:
Here is the same diagnostic with the current PR:
> Copy rho arrays to device after exchange (not to host)

- fbpic/openpmd_diag/checkpoint_restart.py
So far it was not possible to load checkpoints with more than 2 modes. This tiny PR changes that. As a quick test I simulated an off-axis beam with Nm = 4. The plot below shows the Ex field in mode 3 before and after restarting.
> Enable restart for arbitrary modes

- fbpic/fields/fields.py
- fbpic/fields/numba_methods.py
I recently observed that, when using a high number of threads on CPU (e.g. 16 in the case I looked at), the part of the code that erases the duplicated buffers for charge/current can take a significant amount of time.
This is certainly due to the fact that this part is written in numpy, and is not threaded. This PR solves this problem by threading this particular operation, using the usual numba synthax.
> Thread the function that erase charge/current buffers

- fbpic/main.py
- tests/test_continuous_injection.py
While the `Particles` object takes the thermal velocities as argument, the `add_new_species` methods did not.
This PR fixes this. It adds the thermal velocities as arguments, and performs the corresponding boosted-frame transformations if needed (using an approximate formula). 
I also incorporated this change in on of the automated tests.
> Allow the user to specify the temperature, through `add_new_species`

- fbpic/utils/threading.py
For rapid testing/debugging of new features, it is often annoying to have to wait for the JIT compilation (especially if the test itself takes very little compute time).
It turns out that Numba has a [caching option](https://numba.pydata.org/numba-doc/dev/user/jit.html#cache), but this can only be used on CPU, and without threading. 
Therefore, this PR enables the caching flag in the case where the user disables threading.
In other words, when performing quick tests/debugging, it is recommended to use `export FBPIC_DISABLE_THREADING=1`, so that caching is activated and compilation time can be saved.
> Avoid recompilation when threading is disabled

- fbpic/particles/push/cuda_methods.py
- fbpic/particles/push/inline_functions.py
- fbpic/particles/push/numba_methods.py
@PierrePelletier recently noticed that the function defining the vay pusher was duplicated for CPU and GPU, whereas we could use the same "inline function" trick that is used for ionization and gathering.
(i.e. defining the Python function only once, and then compiling it for CPU or GPU when importing it.)
This PR implements the corresponding change.
@PierrePelletier: Thanks again for pointing this out :)
> Reduce duplication for the Vay pusher on CPU and GPU

- fbpic/particles/elementary_process/ionization/ionizer.py
- fbpic/particles/particles.py
- tests/test_ionization.py
A tiny convenience PR to enable user to set a maximum ionisation level for ions. Can be useful in simulations with high-Z elements (e.g. ionization injection in LPA) to avoid creating unnecessary electron species (for better compatibility with #283).
> Enable user to set a maximum ionisation level

- docs/source/api_reference/diagnostics.rst
- docs/source/example_input/ionization_script.py
- fbpic/lpa_utils/bunch.py
- fbpic/main.py
- fbpic/openpmd_diag/__init__.py
- fbpic/openpmd_diag/field_diag.py
- fbpic/openpmd_diag/generic_diag.py
- fbpic/openpmd_diag/particle_density_diag.py
This PR implements a new type of diagnostic: `ParticleDensityDiagnostic`. This outputs the density of one given species, and can be useful e.g. in the case where the plasma is neutral (so as to still see the plasma profile in the output).
Regarding the API: I included this diagnostics in the example script for ionization. I also added the diagnostics in the documentation. Please let me know if you have any suggestion regarding the API.
Regarding the implementation: in order to avoid having to add a new array, the density of the requested species is deposited directly to the array `rho` in interpolation space. However, this will not perturb the on-going simulation, because the deposition does not update the spectral space in this case. (And the simulation only cares about the spectral …
> Close #267 Per-species density diagnostic

- fbpic/fields/utility_methods.py
Close #292  The stencil extent is now calculated with abs(v_comoving) to ensure the correct guard region size is calculated.
> Close #292 Fix stencil reach for galilean scheme

- fbpic/lpa_utils/bunch.py
Since `add_elec_bunch_gaussian` initializes electrons, some users may pass a negative number for the quantities `Q`. This would result in macroparticles with negative weights, i.e. depositing charge/current as if it was a positron bunch, but moving under fields as electrons...
In order to prevent this issue, this PR takes the absolute value of `Q` when initializing an electron bunch.
> Add safe-guard against negative particle weights with `add_elec_bunch_gaussian`

- fbpic/particles/deposition/threading_methods.py
- tests/test_cpu_gpu_deposition.py
It seems that [PR #191](https://github.com/fbpic/fbpic/pull/191) did not completely remove the errors due to out-of-bounds on the CPU *in the case of cubic shape factor*. 
More specifically, for high-radius particles, FBPIC avoids out-of-bound deposition by limiting the radial index of the cell. For cubic shape factors, `ir_cell` is currently capped at `Nr+1` (for depositing into an array of size `Nr+4`: two guard cells on each side). However, because cubic shapes deposit from `ir_cell+0` to `ir_cell+3`, this can reach `Nr+4`, i.e. out-of-bound for Python-based indexing.
This bug should have been detected by the automated test that compares GPU and CPU deposition (since the problem does not occur on GPU). However, this was not the case for 2 reasons:
- This test does not have high-radius …
> Fix cubic CPU deposition

- fbpic/lpa_utils/laser/laser_profiles.py
When using the flattened Gaussian profile with very high orders (~200) the class is returning nan as the E field. This is because the method runs into machine precision problems. This PR fixes the problem by slightly changing the order of calculations.
> Fix precision limitation for flattened gaussian

- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_flattenedgauss_laser.py
In the implementation of the Laguerre-Gaussian modes, the sign of the Gouy phase is incorrect. 
This was not detected previously, because the phase is not checked in the automated tests. 
This bug does affect the flattened Laguerre-Gauss profile, because the relative phase of the different Laguerre-Gauss modes that compose the pulse is then incorrect and produces the wrong overall profile. This was again not detected by the automated tests because they only initialized the flattened Gaussian at focus, where the Gouy phase is 0. Therefore, this pull request also modifies the flattened Gaussian test, so as to initialize the pulse away from focus. With the current `dev` branch, this test fails, but with the correction of this PR, it passes.
> Correct Gouy phase of Laguerre-Gaussian modes

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/cuda_methods.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/particles/injection/continuous_injection.py
- fbpic/utils/printing.py
- tests/test_laser_antenna.py
Fix a bug when the damping region is not entirely filled with plasma after exchange_period steps.
Before this PR, new particles where added only in the physical domain + ~ exchange_period cells ahead of the physical domain. Thus not the entire damping region was filled with plasma. In some cases, non-zero fields can appear in the damping region which can interact with particles injected at different times, causing weird oscillations in e.g. the charge density.
This PR changes this by adding new particles up to the physical domain + the damping region + an additional injection area with n_inject cells. A new parameter n_inject has been added to the Simulation object and the BoundaryCommunicator. It can be set manually but defaults to n_guard/2. It is considered to be part of the damping …
> Add injection area to damping region

- fbpic/openpmd_diag/checkpoint_restart.py
- tests/test_example_docs_scripts.py
This PR adds an optional argument for the functions that write and read the checkpoints. The optional argument points to the path where the checkpoints should be stored.
I also modified the automated tests in order to have them test that new functionality.
> Close #304: Allow changing checkpoint saving folder

- fbpic/lpa_utils/laser/antenna_injection.py
- fbpic/main.py
When the laser antenna crosses the boundary between 2 MPI procs, the current correction gets crazy. This is because rho^{n} is deposited on one MPI rank and rho^{n+1} is deposited on the other MPI rank.
In order to avoid this problem, this PR adds a flag that controls whether the antenna deposits on the current MPI proc (reminder: all MPI rank have a copy of the virtual particles of the antenna ; unlike the actual physical macroparticles).
This flag can only be changed at the beginning of a PIC iteration (i.e. at the same time as we exchange the physical particles between MPI ranks). That way, rho^n and rho^{n+1} are always deposited on the same MPI rank.
For instance, here is the Ez field of an injected laser, around the time when the antenna crosses the boundary between the 2 MPI ranks …
> Fix parallel laser deposition

- fbpic/particles/injection/continuous_injection.py
- tests/test_continuous_injection.py
PR #300 introduced a small bug in the continuous injection routines: when there is no plasma in the box at t=0, the new plasma will only start being injected *after* the damp cells and injection cells, instead of being injected immediately after the end of the physical domain. As a result, simulations typically feature an absence of plasma in the first microns of the simulation.
This PR fixes the bug.
In addition, it adds an automated test to catch similar errors in the future (up to now, the automated tests only checked cases where there is some plasma at t=0 in the box). I also refactored a bit the continous injection test, in order to avoid code duplication.
> Fix continuous injection of plasma when no plasma is originally in the box

- .travis.yml
- README.md
- docs/source/install/install_comet.rst
- docs/source/install/install_cori_edison.rst
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
- fbpic/utils/threading.py
It seems that the latest version of numba (numba 0.42) causes the CPU function `deposit_J_numba_cubic` to crash with the following error:
```
python: /tmp/build/80754af9/llvmdev_1546540969021/work/include/llvm/IR/Instructions.h:3083: llvm::Value* llvm::PHINode::removeIncomingValue(const llvm::BasicBlock*, bool): Assertion `Idx >= 0 && "Invalid basic block argument to remove!"' failed.
Aborted (core dumped)
```
Interestingly the functions `deposit_J_numba_linear` and `deposit_rho_numba_cubic` work fine.
While the problem is being investigated, I think that it would be good to avoid using numba 0.42. This is what this PR does, by:
- Raising an error if FBPIC detects that numba 0.42 is being used
- Modifying the documentation for installation, so as to recommend using numba 0.41
- Modifying …
> Force numba 0.41 in automated tests and installation instructions

- README.md
- docs/source/index.rst
As discussed offline with @RemiLehe, I added additional publications with links to the Readme such that new users can more easily find research papers related to the algorithms of FBPIC. Additionally, we now ask the user to also cite the additional references in their publications if they used the more advanced features of FBPIC.
> Added more publications to README

- .travis.yml
- README.md
- docs/source/install/install_comet.rst
- docs/source/install/install_cori_edison.rst
- docs/source/install/install_jureca.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_titan.rst
- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/cuda_methods_one_mode.py
- fbpic/particles/deposition/threading_methods.py
- fbpic/utils/threading.py
It is seems that issue with `numba 0.42` (see #317) was related to the fact the functions for the shape factors (in the deposition kernels), contained a return statement within an `if` condition. (see the functions `Sz_linear`, etc. in `fbpic/particles/deposition/threading_methods.py`)
In fact, these functions do seem a bit weird, since they have cases that result in no `return` statement (hence what value do they return in this case?!) : see for instance `Sz_linear` for the case `index=2` - although it is never used in practice.
I modified these functions, so as to take the `return` statement outside of the `if` condition (see corresponding code below). 
Although the GPU functions were not causing any issue with numba 0.42, I modified them accordingly, for consistency. I tested the …
> Allow FBPIC to work with numba 0.42

- fbpic/fields/fields.py
- fbpic/lpa_utils/bunch.py
This fixes a small discrepancy between the space-charge calculator and Maxwell solver:
The Maxwell solver smoothes the charge/currents with a user-defined smoother, whereas the space-charge calculator always used the default smoother (one-pass binomial).
> Close #324: Pass the user-defined smoother to the space-charge calculator

- fbpic/lpa_utils/bunch.py
This is a suggestion to solve the issue brought up by @RemiLehe.
The approach would be to remove those particles that result in unphysical gammas. This would of cause change the mean gamma and the std of the distribution but I see no way of avoiding that. 
It is not straightforward to only remove the particles that have a gamma < 1, since there can be the case where ux and uy which are generated according to the emittance of the beam result in a gamma that is larger than the randomly generated gamma and thous would require an imaginary uz for uz,ux,uy and gamma to be consistent.
Therefore, similar as before ux, uy and gamma are calculated independently and from that the square of uz is calculated. Then all the particles are dropped which have a uz**2 < 1. If that happens the user is …
> Close #323: Avoid negative gamma when initialising gaussian bunch

- fbpic/boundaries/particle_buffer_handling.py
There is currently a bug in the particle communication/removal routines on GPU **when all particles of a given species are on the right-hand guard cells**: in this case the particles are not removed from the local domain.
Fundamentally, this is because the code computes the indices `i_min` and `i_max` between which particles should be kept. When all particles are in the right hand guard cells, then `i_min=0` and `i_max=0`. But then a special-case portion of the code (removed in this PR) erroneously sets `i_max=Ntot`.
This special part of the code used to here because the last cells of `prefix_sum` used to be filled with `0`. However this is no longer the case since we introduced `prefill_prefix_sum` in #110.
Therefore that erroneous portion can be safely removed.
> Prevent GPU particle communication/removal bug when all particles are in the guard cells

- tests/test_example_docs_scripts.py
Right now, when make small changes to e.g. how the number of steps are calculated in the example scripts, then the automated tests fail because the script is not able to find/replace the corresponding line. (see e.g. #334 )
This PR makes the test script more flexible, by using regex syntax and e.g. `N_step = .*` syntax to capture arbitrary lines that modify the number of steps.
> Make the script `test_example_docs_scripts.py` more flexible

- fbpic/openpmd_diag/field_diag.py
- fbpic/openpmd_diag/generic_diag.py
- fbpic/openpmd_diag/particle_density_diag.py
- fbpic/openpmd_diag/particle_diag.py
With this PR, the user can either pass the diagnostic period as `period` (an integer) or `dt_period` (a float, in seconds). (This was discussed in the context of #334.)
As a consequence, this makes `period` on optional argument. Following Python synthax, all the following arguments of `ParticleDiagnostic` and `FieldDiagnostic` must be, from a synthax point of view, optional as well. Therefore, I added a few more check to make sure that the user still passes the minimal set of arguments that are strictly necessary.
> Pass the diagnostic period as a physical time (instead of integer)

- docs/source/advanced/boosted_frame.rst
- docs/source/api_reference/diagnostics.rst
- docs/source/example_input/boosted_frame_script.py
- fbpic/openpmd_diag/__init__.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- tests/test_beam_focusing.py
- tests/test_boosted_particle_output.py
- tests/test_ionization.py
I think that the names `BoostedFieldDiagnostic` and `BoostedParticleDiagnostic` might be confusing for some users, e.g. since they are dumping data in the *lab* frame, not the *boosted* frame.
Also, this odd name leads to confusing initializations, as in this example script:
https://github.com/fbpic/fbpic/blob/dev/docs/source/example_input/boosted_frame_script.py#L196-209
where `dt_boosted_...` is passed to the regular diagnostics, but `dt_lab_...` is passed to the `Boosted` diagnostics.
This PR solves this issue by renaming these classes. The `Boosted` classes are kept for backward compatibility, but are not explicitly documented anymore. All the tests and examples now use `BackTransformed`.
> Rename `BoostedDiagnostic` as `BackTransformedDiagnostic`

- docs/source/example_input/boosted_frame_script.py
sorry for being so pedantic, but as `uz_m` is unused it may perturb someone who learns the code, moreover since it's only accepted by `add_new_species` which is not present.
Another thing, since users may use this script as a template for their own simulations, may be theta  ppc number could be also given in a generic form (with some  comment), e.g. `p_nt = 4*(Nm-1)+(Nm==1)` ?  This way they would avoid some nasty instabilities which are not always easy to see on the final result
> removed unused `uz_m` parameter

- docs/source/example_input/boosted_frame_script.rst
- docs/source/example_input/ionization_script.rst
- docs/source/example_input/lwfa_script.rst
- docs/source/how_to_run.rst
This is more of a suggestion:
I often find myself wishing that the example scripts were quickly accessible in the online documentation. (instead of having to download them and open them locally with a text editor). This is what this PR does.
Please compile the doc locally in order to visualize the changes in practice ; please let me know if you agree with these modifications.
> Make the example scripts explicitly visible in the online documentation

- fbpic/lpa_utils/external_fields.py
- fbpic/main.py
- tests/test_external_fields.py
This pull request enables automatic conversion of the `ExternalFields` to the boosted frame.
In order to use this feature, the user simply passes `gamma_boost` to the `ExternalFields` API.
I also expanded the automated tests of the external fields, so as to test them both in the lab frame and in the boosted frame.
> Close #342 Automatically transform the external fields to the boosted frame

- fbpic/openpmd_diag/particle_density_diag.py
This PR adds filtering of the particle density in spectral space before writing it to disk.
This is done by depositing 'rho' and overwriting and filtering 'rho_next' in spectral space before bringing it back to real space and exchanging it between domains. As the diagnostics are called at the beginning of the iteration, 'rho_next' is replaced by the correct charge density later in the PIC loop.
> Add filtering to ParticleChargeDensityDiagnostic

- fbpic/openpmd_diag/checkpoint_restart.py
When using ionization (or tracking) and running on GPU, the particles have an additional attribute `"int_sorting_buffer"`.
In the current version of FBPIC, the code does not resize this array when doing a restart. This can lead to out-of-bound behavior after a restart, and in practice this lead the automated test `test_ionization_script_twoproc` to fail on GPU.
With the present PR, the automated `test_ionization_script_twoproc` passes on GPU.
> Fix restart with ionization on GPU

- fbpic/particles/utilities/cuda_sorting.py
@hightower8083 recently reported that the `dev` branch (which uses `cupy`) leads to an out-of-memory error on typical production simulation. (Many thanks for testing the `dev` branch, and for reporting this error! :sparkles:) 
After looking at it more closely, it seems that this is because some GPU memory is taken by `cupy`'s [memory pool](https://docs-cupy.chainer.org/en/stable/reference/memory.html), and is not available to Numba. This PR fixes the issue.
More precisely: in FBPIC, the `cupy` memory pool should be empty, because we do all the GPU array allocations through Numba, and give the array to `cupy` through zero-copy.
However, in practice, `thrust.argsort` requires to allocate temporary arrays internally. This means that `cupy` *will* take GPU memory for its memory pool *and will …
> Force cupy to release its memory pool

- docs/source/api_reference/lpa_utilities/beam.rst
- docs/source/example_input/boosted_frame_script.py
- fbpic/lpa_utils/bunch.py
As requested in #358 with this PR the bunch initialisation methods now accept the arguments `q` and `m` for the charge and mass of the particle species. For backward compatibility I kept the old functions which now just call the new functions with `-e` and `m_e` as arguments.
> Add methods to initialise beams with arbitrary particle charge

- docs/source/example_input/boosted_frame_script.py
- docs/source/example_input/ionization_script.py
- docs/source/example_input/lwfa_script.py
- docs/source/example_input/parametric_script.py
- fbpic/main.py
- tests/test_ionization.py
Currently, in FBPIC, when the user does not pass `n_e` (i.e. `n_e` is `None`), no macroparticles are created, but the the electron species itself is still created (and is empty of any macroparticles).
This is not very elegant, and usually forces users to explicitly remove that electron species with:
```
sim.ptcl = []
```
With this PR, no electron species is created, when `n_e` is None. Note that this breaks backward-compatibility in some cases, but these cases are expected to be rare.
Examples where this breaks backward capability:
- The user creates the `Simulation` object with `n_e=None`, forgets to do `sim.ptcl = []`, calls `sim.create_new_species` and then addresses particles (e.g. in `ParticleDiagnostics`) by indexing `sim.ptcl` (e.g. `sim.ptcl[1]`) instead of addressing them with …
> Do not create particle species, when `n_e` is `None`

- fbpic/lpa_utils/bunch.py
- fbpic/picmi/simulation.py
In the PICMI standard, the user can choose whether the initial self fields should be initialized or not.
In order to ensure compatibility, I added the option `initialize_self_fields` to the function that add a bunch to the simulation. (Only the functions with the new API, not the `add_elec_bunch` functions.)
Note that this is not yet fully PICMI-compliant, since a bunch which is loaded with an `AnalyticalDistribution` will not have the option, through FBPIC, to have its space-charge initialized.
> Add the option `initialize_self_fields`

- fbpic/particles/injection/ballistic_before_plane.py
As reported in #385, the ballistic injection has a bug when using it in lab-frame simulations.
This pull request fixes the bug ; I checked it locally by adding a gaussian particle beam to the standard LWFA example, with an injection plane.
> Fix bug in ballistic injection for lab-frame simulation

- fbpic/openpmd_diag/boosted_particle_diag.py
`math.ceil` returns an [integer in Python 3](https://docs.python.org/3.7/library/math.html#math.ceil) but a [float in Python 2](https://docs.python.org/2/library/math.html#math.ceil).
The fact that the returned result is a float caused the boosted-frame diagnostic to fail on GPU: see #388. It is a bit surprising that this error only shows up now, but I am guessing that maybe some of our dependencies were recently updated.
The current PR forces the return result to be an integer.
> Fix Python 2 error in particle diag

- fbpic/openpmd_diag/__init__.py
- fbpic/openpmd_diag/inputdeck_diag.py
- fbpic/openpmd_diag/inputscript_diag.py
This pull request would add an option for the user to store the input deck used to run the simulation as an attribute in hdf5 files via an InputDeckDiagnostic. This could allow for easy checks of exactly what parameters were used in the simulation at a later, when the input deck may have gotten lost. 
Additionally, an arbitrary list of other parameters can be written as attributes into the hdf5 files. For example, if the simulation was part of a large parameter scan (f in np.linspace(1, 3, 0.25)) the user can store the parameter range and the value used in the current simulation. This could simplify automatic analysis later on.
> Adding an input deck diagnostic

- fbpic/main.py
The documentation did not explicitly state that one only needs 1 particle in the theta direction when `Nm=1`.
Thanks a lot to @abonatto for pointing this out to me!
> Update documentation on number of modes

- fbpic/main.py
- fbpic/utils/threading.py
This PR tells the user to install an earlier version of numba instead.
> Close #393: fbpic does not work with new numba release (0.46) on GPU

- fbpic/particles/gathering/cuda_methods.py
- fbpic/particles/gathering/cuda_methods_one_mode.py
- fbpic/particles/gathering/threading_methods.py
- fbpic/particles/gathering/threading_methods_one_mode.py
This PR prevents the high-radius particles (i.e. outside the simulation box) from gathering fields. This fixes a bug in which high-radius particles could get "reflected" into the box (as reported e.g. by @danielseipt in #369). 
This is implemented by adding an `if` condition directly in the gathering kernels. Note that the position of the `if` condition is different in the generic `one_mode` kernels and in the specialized kernels that gather for `m=0` and `m=1` simultaneously. This is because: 
- in the case of the `one_mode` kernels, the fields are set to 0 (after being allocated with arbitrary values) *before* calling the gathering kernels. Therefore, the kernel can be mostly skipped for high-radius particles.
- in the case of the specialized kernels, the fields are not set to 0 …
> Do not gather field for the particles that are outside simulation box

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/cuda_methods.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/field_diag.py
- fbpic/openpmd_diag/particle_density_diag.py
- fbpic/utils/printing.py
- tests/test_laser_antenna.py
This PR adds the possibility to add `nr_damp` cells in a simulation.
Here is a list of the changes:
- 2 new arguments have been added to the API of the `Simulation` object: `nr_damp` and `r_boundary` (which can be either `"reflective"` - the default - or `"open"`). Note that the radial damp cells are only added if `r_boundary` is `"open"`. For backward compatibility, the number of damp cells and boundary in the `z` direction are still called `n_damp` and `boundaries` (without an explicitly `z`).
- In the `BoundaryCommunicator` object: `self.n_damp` has been replaced by `self.nz_damp` throughout the code, and a new attribute `self.nr_damp` has been added. In addition, 2 new methods have been added: `get_Nr` and `get_rmax`, which have an optional argument `with_damp`. They return the …
> Add the possibility to add `nr_damp` cells radially, in preparation for PMLs

- fbpic/main.py
- fbpic/particles/particles.py
During the PIC loop, we typically: 
- gather the E and B fields into the arrays with one element per particle
- then use these fields to push the particles and/or perform ionization
However, when running on GPU, particles arrays may be sorted and rearranged between the time at which the field are gathered and the time at which they are used. (This may happen because of charge/current deposition and/or boosted-frame diagnostics and particle-density diagnostics.) **In the current `dev` branch, when particles are rearranged, the particle arrays for the E and B field are NOT rearranged.** This means that, if the fields are used after the particles have been rearranged, their values will be invalid. (For instance, this caused spurious ionization in #396.)
This PR fixes the issue by rearranging …
> Close #396: Keep field arrays sorted whenever needed

- fbpic/boundaries/moving_window.py
- fbpic/fields/fields.py
- fbpic/fields/interpolation_grid.py
- fbpic/fields/spectral_grid.py
- fbpic/main.py
When using PML, the fields are *split* (each split component is pushed with a different part of the curl term in the Maxwell equation, and only one of the two component is damped in PML cells while the other one is undamped).
In FBPIC, we will represent this as:
- `Er_pml`, `Et_pml` (in interpolation space) and `Ep_pml`, `Em_pml` (in spectral space): represent the split component which **is** damped.
- The pre-existing`Er`, `Et` (in interpolation space) and `Ep`, `Em` (in spectral space): represent the **sum** of the two split component (damped and undamped).
Choosing to store the *damped* component and the *sum* of the split components is equivalent to storing  the *damped* and *undamped* components  (since we can go from representation to the other by adding/substracting the damped …
> Prepare PML split field structures

- docs/source/api_reference/lpa_utilities/laser.rst
- docs/source/api_reference/lpa_utilities/laser_profiles/few_cycle.rst
- fbpic/lpa_utils/laser/__init__.py
- fbpic/lpa_utils/laser/laser_profiles.py
- tests/test_fewcycle_laser.py
When a laser pulse is so short that it contains **only a few laser cycles**, the standard Gaussian profile `GaussianLaser` is not well-adapted, as it does properly take into account spatial-temporal correlations for tightly-focussed pulses. In particular, when initializing a `GaussianLaser` with a short duration **out of focus** in FBPIC, the later profile **at focus** will not be the expected one.
This can be fixed by using the new `FewCycleLaser` introduced by this PR. I also added an automated test that checks that this laser has the proper profile after propagation to focus.
Here is how this pulse looks like:
- out of focus, at the beginning of the test:
- at focus, at the end of the test:
By contrast, here is how `GaussianLaser` looks like after propagation to focus, using the same …
> Implement few-cycle laser pulse profile

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/cuda_methods.py
- fbpic/boundaries/field_buffer_handling.py
This is the last of the "mundane" PR that prepares the PML structure: it performs the MPI exchange of the PML fields. 
More precisely, when using the PML, the MPI buffers for E and B are made larger, so that they can hold `Er_pml`/`Et_pml` and `Br_pml`/`Bt_pml`, and these fields are copied to/from these buffers.
> Implement MPI exchanges for PML

- fbpic/picmi/simulation.py
For simulations with ionization, it is often convenient to create an electron species with no macroparticles initially. (The macroparticles will come from the ionization process of ions.)
In this case, the `layout` argument would typically be `None`. This PR corrects FBPIC so that it can handle the case `layout=None`.
> Add the possibility to have an empty species in PICMI

- fbpic/main.py
- fbpic/utils/cuda.py
`cupy` and `numba` need to have compatible versions:
- numba<=0.45 is only compatible with cupy<=6
- numba>=0.46 is only compatible with cupy>=7
(see e.g. [this issue](https://github.com/numba/numba/issues/4661))
With this PR, the code stops execution when a version incompatibility is detected, and the user is prompted to install the latest version of either package.
> Fix potential incompatibilities between numba and cupy

- fbpic/boundaries/field_buffer_handling.py
The communications of PML fields has a typo, in the case where the code runs on GPU.
This PR fixes the typo. The code can be tested by doing:
```
mpirun -np 2 python test_pml.py
```
(and changing `n_order` to `32` in `test_pml.py`)
Many thanks to @Kookjin for testing the `finalized_pml` branch and reporting an issue in GPU-MPI simulations!! :sparkles:
> Fix bug in GPU-MPI communications of PML

- docs/source/example_input/boosted_frame_script.py
- docs/source/example_input/ionization_script.py
- docs/source/example_input/lwfa_script.py
- fbpic/boundaries/boundary_communicator.py
- fbpic/main.py
- fbpic/picmi/simulation.py
- fbpic/utils/printing.py
- tests/test_pml.py
This updates the API for the PML:
- `boundaries` should now be passed as a dictionary ; e.g. `boundaries = {'z':'open', 'r':'reflective'}` without PML and `boundaries = {'z':'open', 'r':'open'}` for PML.
- `n_damp` should also be passed as a dictionary (although users usually don't pass this, and use the default instead).
Note that the previous API (single string. e.g.`boundaries='open'`) still works (for backward compatibility) but will raise a warning, recommending to pass a dictionary instead.
A few minor changes related to the API were also added:
- The PICMI interface can now also activate the PML. (by passing `'open'` for the `r` boundary)
- The `r` boundary (`'open'` or `'reflective'`) is printed when doing `verbose_level=2`.
- The default example scripts now use the new API
> Update the API of the PML

- fbpic/fields/spectral_grid.py
When profiling a run with PML on GPU today, I noticed many Host-Device copies. 
It turns out that I was using the CPU arrays for the PSATD coefficients in the PML push kernel.
This PR fixes the issue ; I checked that this removes the Host-Device copies.
> Use device version of PSATD coefficients for PML push

- fbpic/main.py
- fbpic/particles/gathering/cuda_methods.py
- fbpic/particles/gathering/cuda_methods_one_mode.py
- fbpic/particles/gathering/threading_methods.py
- fbpic/particles/gathering/threading_methods_one_mode.py
- fbpic/particles/particles.py
This PR is very similar to #398 ("Do not gather field for the particles that are outside simulation box"), but while #398 prevents particles from gathering fields *when they are outside the full simulation grid (which includes PML cells)*, the current PR prevents particles from gathering fields *when they are outside the physical domain (which excludes PML cells)*.
Thus, with this PR, particles will not gather fields from the PML, and will thus propagate in straight lines.
In practice, this PR modifies the code in the same places that #398 did, but checks if `r < rmax_gather` where `rmax_gather` is given by `comm.get_rmax( with_damp=False )` (`with_damp=False` excludes the PML) - see the file `particles.py`. As consequence, the code has been modified so that the `BoundaryCommunicator` …
> Gather only for particles that are inside the physical box

- docs/source/how_to_run.rst
Thanks to @ax3l, `openPMD-viewer` is now on `conda-forge` 🌟 ❤️ :
https://anaconda.org/conda-forge/openpmd-viewer
This PR updates the installation instructions accordingly, in FBPIC's documentation.
> Update installation instructions for openPMD-viewer

- fbpic/fields/fields.py
- fbpic/lpa_utils/bunch.py
- fbpic/particles/particles.py
- fbpic/utils/cuda.py
- tests/test_periodic_plasma_wave.py
- tests/test_uniform_rho_deposition.py
This is a PR that **prepares** the code for a switch of some functionalities from `numba.cuda` to `cupy`.
More specifically, in FBPIC, we sometimes pass CPU (`numpy`) arrays to `numba.cuda` kernels. This essentially happens when we call `deposit` outside of the main PIC loop. (e.g. when computing the initial space-charge fields). In this case, the code calls the `numba.cuda` kernels for charge/current deposition, but the arrays are still on the CPU, because the execution has not gone through the set of `send_to_gpu` functions that are the beginning of the main PIC loop.
In this case, `numba.cuda` kernels are quite forgiving, as they then automatically copy the `numpy` arrays to GPU before the kernel and back to CPU after the kernel.
However, this will not be the case with `cupy` kernels: …
> Implement context manager to move data to GPU

- fbpic/boundaries/cuda_methods.py
- fbpic/boundaries/moving_window.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/boundaries/pml_damping.py
- fbpic/fields/cuda_methods.py
- fbpic/fields/spectral_transform/cuda_methods.py
- fbpic/lpa_utils/laser/antenna_injection.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/cuda_methods.py
- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/cuda_methods_one_mode.py
- fbpic/particles/elementary_process/compton/cuda_methods.py
- fbpic/particles/elementary_process/cuda_numba_utils.py
- fbpic/particles/elementary_process/ionization/cuda_methods.py
- fbpic/particles/gathering/cuda_methods.py
- fbpic/particles/gathering/cuda_methods_one_mode.py
- fbpic/particles/push/cuda_methods.py
- fbpic/particles/tracking/tracking.py
- fbpic/particles/utilities/cuda_sorting.py
- fbpic/utils/cuda.py
This pull request implements a custom decorator mimicking Numba's `@cuda.jit` which compiles python functions to CUDA kernels. It uses the Numba JIT compilation to produce PTX code, which is then passed to Cupy to create a RawKernel. This way, the smaller API overhead from Cupy is utilized while retaining the flexibility of Numba JIT compilation.
> Use a custom decorator to compile CUDA kernels to cupy

- fbpic/main.py
In previous versions of FBPIC, we were allowing `numba<= 0.45` on GPU - provided that `cupy<=6` was also installed. 
However, now that GPU arrays are `cupy` arrays, this is no longer possible. This is because passing `cupy` arrays of size 0 to a `numba.cuda` kernel (which happens e.g. when a given species has 0 macroparticles in FBPIC) causes the code to crash, with `cupy<=6`. (See [this issue](https://github.com/numba/numba/issues/4140) for more details.)
Note that this is still the case with the new decorator (PR #431), since we still pass cupy arrays (potentially of size 0) to `numba`'s `specialize` function - which is enough to cause the above-mentioned crash.
As a result, we now need `cupy>=7`, which in turn imposes `numba>=0.46` and Python 3 (when running on GPU).
> For GPU: check cupy, numba and Python version.

- fbpic/particles/elementary_process/cuda_numba_utils.py
- fbpic/particles/elementary_process/ionization/ionizer.py
This PR moves the cumsum calculated after the particle ionization to the GPU using `cupy.cumsum`. This helps reduce overhead since much less data needs to be copied from device to host and back.
> Move the cumsum in the ionization kernels to the GPU

- fbpic/particles/elementary_process/compton/compton.py
- fbpic/particles/elementary_process/cuda_numba_utils.py
This moves the calculation of the cumsum to the GPU in the Compton scattering module, analogously to the ionization module.
> Moved cumsum to GPU in Compton kernels

- fbpic/main.py
When allocating data on the GPU, cupy by default does not free memory when it is not needed anymore, instead caching the memory so that future allocations become faster. This is expected behaviour and does not lead to out-of-memory crashes since cupy detects when the memory pool is full and clears it when needed. 
However, this leads to the GPU memory filling up even for small simulations, which might be confusing to users. Additionally, it might conflict with other GPU libraries which are not aware of cupy. This PR forces cupy to clear its memory pool at each exchange period to remedy this.
> Added call to clear cupy memory pool for each exchange period

- README.md
Travis CI is encouraging repos to transition from the legacy `travis-ci.org` interface to the new `travis-ci.com` interface. 
Thanks to @ax3l's help, I made the corresponding changes on the Travis CI side, for FBPIC. This PR simplies updates the badges, so that they reflect the status on `travis-ci.com`.
> Update badges for new Travis interface

- fbpic/picmi/__init__.py
- fbpic/picmi/simulation.py
This PR adds support for PICMI's `UniformDistribution` in FBPIC. (Before this PR, the only other supported distribution for evenly-spaced particles is the `AnalyticalDistribution`.)
In addition, this PR incorporates a small change to the `step` function: this is because picmi allows the number of timesteps to be passed either to `step`, or the the `Simulation` `__init__` function.
> PICMI: Add uniform distribution and default number of steps

- docs/source/install/install_juwels.rst
- fbpic/boundaries/boundary_communicator.py
- fbpic/utils/mpi.py
Since the last version of FBPIC, GPUdirect (i.e. direct MPI communication between GPUs) no longer works because the `numba` arrays have been replaced by `cupy` arrays. This PR fixes this issue.
It should be noted that GPUdirect only works with the development version of `mpi4py` (3.1.0a0), where a new interface for this functionality has been introduced (see [the cupy documentation](https://docs-cupy.chainer.org/en/stable/reference/interoperability.html)).
The PR also updates the documentation regarding installation on JUWELS to include GPUdirect.
> Fix GPUdirect for cupy arrays

- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/cuda_methods_one_mode.py
- fbpic/particles/deposition/particle_shapes.py
- fbpic/particles/deposition/threading_methods.py
In the current code, the particle shape factors are defined redundantly at three seperate locations. This PR moves them to a single file and imports them where needed.
> Move shape factors to seperate file

- .travis.yml
It seems that Travis builds are stalling (and therefore failing) when using the new numba 0.49. 
While we investigate this problem, this PR forces Travis to use a lower version, so that builds can still work.
> Do not use numba 0.49 for Travis builds

- .travis.yml
- fbpic/utils/threading.py
**Please merge #444 first**
Starting with numba 0.45, the option `cache=True` is available even when `parallel=True`. This makes compilation much faster. Therefore, this PR enables this option for all JIT compilation in FBPIC.
> Enable caching in `numba.jit`, even when threading is activated

- fbpic/particles/utilities/utility_methods.py
In FBPIC, the antenna always deposits with linear shape factor ; therefore, this PR removes the code for cubic shape factors.
> Remove code for cubic shape in antenna deposition

- .travis.yml
We were using an old Linux environment for the Travis tests ; this PR changes this to the current default environment (Xenial).
> Update travis environment

- fbpic/fields/interpolation_grid.py
- fbpic/particles/deposition/cuda_methods.py
- fbpic/particles/deposition/cuda_methods_one_mode.py
- fbpic/particles/deposition/threading_methods.py
- fbpic/particles/utilities/utility_methods.py
This refactors the code for the Ruyten correction, by removing the `if` condition in the deposition kernels and instead add an element in the Ruyten array (which corresponds to the particles in the first half of the first cell, radially.)
This should be equivalent to the previous implementation - except for the laser antenna: it seems that the laser antenna was using a non-zero Ruyten coeffficient for the particles in the first half of the first cell in the previous code.
> Refactor the code for Ruyten correction

- fbpic/boundaries/boundary_communicator.py
- fbpic/boundaries/field_buffer_handling.py
- fbpic/boundaries/moving_window.py
- fbpic/boundaries/particle_buffer_handling.py
- fbpic/boundaries/pml_damping.py
- fbpic/fields/interpolation_grid.py
- fbpic/fields/psatd_coefs.py
- fbpic/fields/spectral_grid.py
- fbpic/fields/spectral_transform/fourier.py
- fbpic/fields/spectral_transform/hankel.py
- fbpic/fields/spectral_transform/spectral_transformer.py
- fbpic/lpa_utils/laser/antenna_injection.py
- fbpic/main.py
- fbpic/openpmd_diag/boosted_field_diag.py
- fbpic/openpmd_diag/boosted_particle_diag.py
- fbpic/openpmd_diag/checkpoint_restart.py
- fbpic/particles/elementary_process/compton/compton.py
- fbpic/particles/elementary_process/cuda_numba_utils.py
- fbpic/particles/elementary_process/ionization/ionizer.py
- fbpic/particles/particles.py
- fbpic/particles/tracking/tracking.py
- fbpic/particles/utilities/cuda_sorting.py
- fbpic/utils/cuda.py
- tests/unautomated/test_cuda_transform.py
When `cupy` is not installed, *but* the machine on which FBPIC is run has a GPU, the code crashes (even when setting `use_cuda=False`). 
This is because in this case `cuda_installed` is `True`, but `cupy_installed` is `False`. In this case, because of some inconsistencies in the `import` statements, `fbpic` tries to import some functions that depend on `cupy`.
In order to fix this, I created a single flag `cuda_installed`, which is `True` *only* if both `numba.cuda` and `cupy` are available.
Most of the changes in this PR are systematic (i.e. remove `cupy_installed` in various places). I would still recommend to have a look at `main.py`, since I changed the warning message there.
> Use single flag `cuda_installed` for both `cupy` and `numba.cuda`

- README.md
- docs/source/install/install_comet.rst
- docs/source/install/install_juwels.rst
- docs/source/install/install_lawrencium.rst
- docs/source/install/install_local.rst
- docs/source/install/install_summit.rst
- fbpic/main.py
Downloading the latest numba from `conda` typically results in an compilation error on GPU, which can be difficult for users to diagnose. (see #458 )
Therefore, this PR modifies the documentation to recommend the installation of `numba 0.49`, and adds an error message when `numba 0.50` is detected.
> Impose numba 0.49

- fbpic/lpa_utils/laser/antenna_injection.py
When antenna is not in the simulation domain it still updates velocities of virtual particles, and wastes a bit of resources. 
Here an inactive mode is added when antenna is not in the simulation domain.
> inactive mode for absent antennas 

- fbpic/lpa_utils/external_fields.py
This PR improves the performance of external fields when on GPU.
In the current code, `numba.vectorize` is used to compile the user-defined field functions for GPU. This is slow and also causes `memcopy` operations every call. In this PR, `cuda.jit` is instead used to compile an inline function, which is then embedded in a standard kernel compiled with `compile_cupy` to benefit from cupy's smaller kernel call overhead.
> Improve performance of external fields on GPU

- fbpic/lpa_utils/external_fields.py
- fbpic/utils/cuda.py
This PR fixes a bug introduced in the latest overhaul of the external fields on GPU (#470) where scoping issues can lead to wrong results for multiple external fields. This was due to the external field GPU kernels being compiled not at the time of definition, but at the time of the first call.
To fix this, this PR adds an option to immediately specialize a GPU kernel with given function signature for the `compile_cupy` decorator. This option is then used for the external fields.
> Fix scoping issues for external fields on the GPU

- fbpic/picmi/simulation.py
With this PR the order of the finite stencil along z for the Maxwell field solver is read directly from the member `stencil_order` (vector of integers) of the class `PICMI_ElectromagneticSolver`, instead of being hard-coded as `n_order=32`.
If `stencil_order` is not initialized in the solver, the default is set to `n_order=-1`, which corresponds to infinite order and matches the default in the `Simulation` class. Not sure which default order you would like to keep for the PICMI interface.
> PICMI: read PSATD order in z from field solver

- setup.py
This adds the `picmi` install option.
More specifically, when doing:
```
pip install fbpic[picmi]
```
this will automatically download the extra dependencies required to run fbpic with a PICMI script.
> Add install option for PICMI

- fbpic/lpa_utils/laser/antenna_injection.py
This PR reverts the change from #461, because we recently observed that it unexpectedly changed the results of some recent boosted-frame simulations. 
@hightower8083 Sorry for the delay in incorporating this feature. I'll investigate the changes and will merge into `dev` again once this is cleared up.
> Revert antenna to previous behavior

- fbpic/lpa_utils/laser/laser_profiles.py
This PR greatly improves the performance of the Flattened Gaussian laser profile. This is especially notable when used together with the laser antenna, where the laser profile calculation has before often dominated the runtime of a simulation when the order of the Flattened Gaussian is large (e.g. for N=100).
To achieve this, the Flattened Gaussian is implemented as a recursive sum instead of the sum over Laguerre-Gaussian modes it was before. This reduces the number of iterations needed from N! to N, where N is the order of the Flattened Gaussian.
> Improved performance of Flattened Gaussian laser

- fbpic/openpmd_diag/boosted_particle_diag.py
When the user passes an invalid quantity to the `BackTransformedParticleDiagnostic` (e.g. request to output `uw` instead of `uz`), instead of printing a helpful error message, `fbpic` was hitting an undefined variable (`particle_var`) and was printing a confusing message.
This fixes the issue.
> Fix handling of error in particle output

- fbpic/fields/numba_methods.py
- fbpic/particles/elementary_process/ionization/numba_methods.py
The while loops in some function were introduced a long time ago, due to a quirk in an old version of numba.
But I think that this quirk has been fixed since a long time. As a result, I tried to convert those while loops to for loops.
> Convert while loops to for loops

- fbpic/utils/printing.py
When using `verbose=2`, the node name was not printed *for single-MPI simulations*.
Yet this information can be useful even for single-MPI simulation. This PR corrects this.
> When using `verbose=2`, print node name whenever possible

- .github/workflows/unix.yml
Python 2.7 is no longer officially maintained, and it seems that some FBPIC dependencies are now failing - when installed from Python 2.7 channels.
This PR deactivates Python 2 in the automated tests. From now on, only Python 3 will be tested.
> Deactivate Python 2.7 in automated tests

- docs/source/install/install_comet.rst
- docs/source/install/install_juwels.rst
- docs/source/install/install_local.rst
Some links to Anaconda pages in the documentation are broken. This PR proposes to fix them.
> Update anaconda/miniconda links

- fbpic/lpa_utils/boosted_frame.py
The algorithm to do the boost in `BoostConverter.boost_particle_arrays` was subject to loss of numerical accuracy. The primary reason is its use of vz which can be very close to 1, causing a loss of precision. One result of the loss of precision is that the transverse momenta were coming out different than the input values, even though the transform should not affect them.
The algorithm it was replaced with applies the transform directly to the momenta. The vz is only calculated to advance the particle position. The code is quite a bit simpler and the direct copy of the transverse momenta is explicit.
Note that I use a copy to get new_ux and y to avoid any overwriting issues. If the ux and uy passed into this routine are not used for anything afterwards, the copy is not needed.
> Fix the particle boost to use a less numerically lossy algorithm

- fbpic/particles/utilities/cuda_sorting.py
- fbpic/utils/printing.py
It seems that the code that catches memory error was not updated when we switched from the `numba.cuda` allocation to the `cupy` allocation.
I also added the decorator `catch_gpu_memory_error` around the sorting routine (`cupy` needs to allocate temporary arrays under the hood, when performing the Radix Sort).
> Catch cupy memory error

- fbpic/main.py
- fbpic/utils/cuda.py
- fbpic/utils/mpi.py
- fbpic/utils/printing.py
- fbpic/utils/threading.py
This PR prints a unique GPU ID when setting `verbose_level = 2` in the `Simulation` object.
It also checks for oversubscription of GPUs, i.e., if the same GPU was selected by more than one rank, in which case a warning is printed.
The PR also required minor improvements to the version checking of the `cupy` and `numba` package.
> Detect UUID and check for GPU oversubscription

- fbpic/utils/cuda.py
This fixes #528, a crash on GPUs where cupy, for whatever reason, gives back an invalid-length GPU UUID.
> Fix crash for invalid-length GPU UUIDs

- .github/workflows/unix.yml
- fbpic/fields/spectral_transform/hankel.py
Cupy 9 requires a helper GPU array (instead of a scalar) that is passed as an argument to the cuBLAS dgemm call during the Hankel transform.
> Fix cupy 9 compatibility

- fbpic/fields/spectral_transform/mkl_fft.py
When installing MKL with `pip`, the name of the library file happens to be slightly different.
This PR allows FBPIC to find the corresponding file.
> Allow FBPIC to use MKL provided by `pip`

- fbpic/utils/cuda.py
This PR fixes a bunch of warnings that appear in the output for Numba versions 0.53 and greater during kernel compilation on GPU, as well as incompatibilities with upcoming versions of numba. It also slightly refactors the cupy kernel launcher by moving the code that creates a cupy kernel into a seperate function to reduce redundancy.
I tested the PR on GPU with numba versions 0.50.1, 0.53.1, and the current dev version (0.54.0-dev).
> Fix warnings for Numba 0.53 and greater

- fbpic/lpa_utils/laser/longitudinal_laser_profiles.py
- fbpic/lpa_utils/laser/transverse_laser_profiles.py
This adds the calculation of the integrals of the different profiles. This will be useful in order to initialize a laser of a given desired energy.
For the flattened gaussian laser, I tested the validity of the formula with the following code:
```
import numpy as np
import matplotlib.pyplot as plt
from fbpic.lpa_utils.laser.transverse_laser_profiles import FlattenedGaussianTransverseProfile
w0 = 15.3e-6
x = np.linspace(-10*w0, 10*w0, 2000)
y = np.linspace(-10*w0, 10*w0, 2000)
x2d, y2d = np.meshgrid( x, y)
plt.figure(figsize=(6,6))
for N in range(0,10,2):
profile = FlattenedGaussianTransverseProfile(w0, N)
plt.subplot(211)
plt.plot( 1.e6*x, profile.evaluate(x, 0, 0).real, label=N )
plt.subplot(212)
E = abs(profile.evaluate(x2d, y2d, z=0))
integral = (E**2).sum()*(x[1]-x[0])*(y[1]-y[0]) …
```
> Squared profile integrals

- fbpic/lpa_utils/laser/__init__.py
- fbpic/lpa_utils/laser/laser_profiles.py
- fbpic/lpa_utils/laser/longitudinal_laser_profiles.py
- tests/test_parax_approx_laser.py
This PR introduces a new laser, the `ParaxialApproximationLaser`, which provides an easy way for  users to create custom laser profiles. For example, a laser pulse that has a flattened Gaussian transverse profile and a chirped Gaussian longitudinal profile can now be created as follows:
```python
from fbpic.lpa_utils.laser import ParaxialApproximationLaser, \
GaussianChirpedLongitudinalProfile, FlattenedGaussianTransverseProfile
longitudinal_profile = GaussianChirpedLongitudinalProfile(tau, z0, lambda0, phi2_chirp)
transverse_profile = FlattenedGaussianTransverseProfile(w0, N, zf, lambda0)
laser_profile = ParaxialApproximationLaser(longitudinal_profile, transverse_profile, E_laser, theta_pol=0.)
```
Note that the pulse energy `E_laser` is passed as a parameter to this new laser profile, …
> Paraxial Approximation Laser

- fbpic/utils/mpi.py
The current mpi4py version check fails when using mpi4py 4.0. Adding another if statement seems to fix this.
> Added if to handle mpi4py 4.0

- README.md
- docs/source/install/install_local.rst
This adds documentation on how to install the PICMI dependencies:
> Close #574: Document how to install the PICMI dependencies

- fbpic/main.py
- fbpic/picmi/simulation.py
This fixes several issues with the picmi interface.
- Changes were needed for the grid since the single quantities like `nr` and `zmax` are no longer saved as attributes
- Allowed `None` to be used for the bounds of the plasma
- Added diagnostics for names like `E` and `B`
- Added fbpic specific arguments for the Simulation class
- Added a change to the main loop so that the diagnostics are written out for the last time step (is there a better way to do this?)
> Fixes for picmi

- docs/source/install/install_local.rst
Feedback received from @ax3l while troubleshooting local installation issues: calling `python setup.py install` is considered deprecated in the Python world.
> Update Docs for Local Install from Source

- fbpic/picmi/simulation.py
This updates the calculation of `dt` in PICMI so as to ensure that it takes `dr` into account.
> Fix PICMI calculation of dt so that it is consistent with other codes

- fbpic/picmi/simulation.py
In the PICMI interface, the list of fields that each MPI rank needs to output was determined by a Python `set`, which was then converted to a list. However, the order of the elements is not deterministic, in this conversion. 
Therefore, different MPI ranks (for the same simulation) could end up with having this list in different orders. This is problematic, since, in the diagnostic code, each MPI rank loops through the field by using this list, and performs MPI Gather with the other ranks within this loop. This means that the MPI gather was potentially gathering different fields (e.g. `Jy` and `Ex`) into the same array!
This is now fixed by imposing the order of elements.
Closes #587
> Fix PICMI field diagnostic

- docs/source/example_input/boosted_frame_script.py
- docs/source/example_input/ionization_script.py
- docs/source/example_input/lwfa_script.py
- docs/source/example_input/parametric_script.py
This PR updated the example scripts to use the newer laser API. First, a laser profile is created, e.g. through `GaussianLaser()`, and it is then added to the simulation by calling the function `add_laser_pulse(sim, laser_profile, ...)`. The boosted frame example now uses the `antenna` method to add the laser pulse.
> Use add_laser_pulse in example scripts

- fbpic/fields/spectral_transform/mkl_fft.py
MKL numbers libraries now. Anaconda seems to have them numbered with '1'. Implemented in the same manner as it is done for Linux.
> Make the install of MKL more flexible for Windows

- fbpic/boundaries/boundary_communicator.py
With the latest version of `numpy`, one gets the following warning in FBPIC:
```
DeprecationWarning: /home/rlehe/Documents/codes/fbpic/fbpic/boundaries/boundary_communicator.py:1110:
`np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
As suggested by the warning, this PR uses `np.complex128` instead of `np.complex` (as in much of the rest of the code.)
> Silence numpy warning regarding `np.complex`

- fbpic/utils/cuda.py
This PR addresses #602 attempts to remove the use of `ptx`, which is not supported anymore in numba `0.56`.
The fix is based on this line of numba code:
https://github.com/numba/numba/pull/8191/files#diff-ad6746f9263e40f10fa2a85537c0da56a1a8abfd7a0743ec0c06e3a14e3df0e7L193
Importantly, this change is in an `if` condition, based on the detected version of `numba`, so that the code remains compatible with previous versions of `numba`.
**Current status**:
Update: the issue described below was fixed in `numba 0.56.2`, thanks to [this PR](https://github.com/numba/numba/pull/8310>). As a result, FBPIC does not work with `numba 0.56.0` on GPU, but works with both previous versions of `numba` and later versions of `numba`.
~~The fix works with `numba 0.55.2` (for which it is however not required, …
> Make FBPIC compatible with numba version 0.56: Remove use of `ptx`

- fbpic/lpa_utils/laser/transverse_laser_profiles.py
This is a follow-up on https://github.com/fbpic/fbpic/pull/302.
This previous PR only corrected the `LaguerreGaussProfile` but failed to correct the `DonutLikeLaguerreGaussProfile`.
> Correct Gouy phase for Donut-like Laguerre-Gauss pulse

- README.md
Heroku is no longer free. As a workaround, I created an invite link via Slack that expires after 400 invites.
> Alternative Slack invite link

- fbpic/picmi/__init__.py
- fbpic/picmi/simulation.py
This PR adapts FBPIC for the following change in PICMI:
https://github.com/picmi-standard/picmi/pull/75
and thereby fixes the automated tests.
> Adapt FBPIC for new PICMI ionization interface

- fbpic/main.py
- fbpic/particles/particles.py
Hi, 
I added a few tiny modifications to be able to create particle species as tracers, ie particles that move as particles with the given mass and charge should, but contribute no current. This allows these to be used as passive probes of the plasma.
The attached video shows what this does: when creating a density bump in a plasma and shooting a high intensity laser through it, the background plasma is not affected at all if the species is defined as a tracer particle. If the bump is made of normal electrons, the background plasma is affected by the extra injected charge. I also have a script I used for this, but can't seem to attach it here...
Cheers,
Kris
https://user-images.githubusercontent.com/4076141/210784309-99c3e69d-66c1-40d2-bfe0-ea88f08dd362.mp4
> Added particle tracer option

- fbpic/utils/cuda.py
The logic in `cuda.py` was incorrect. This PR fixes it and allows the code to run with numba 0.57.0.
> Fix logic for numba version 0.57.0
